// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AgentActivity {
    pub agent_id: String,
    pub state: String,
    pub last_tool_event: Option<String>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for AgentActivity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AgentActivity`.
///
/// Provides typed access to columns for query building.
pub struct AgentActivityCols {
    pub agent_id: __sdk::__query_builder::Col<AgentActivity, String>,
    pub state: __sdk::__query_builder::Col<AgentActivity, String>,
    pub last_tool_event: __sdk::__query_builder::Col<AgentActivity, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<AgentActivity, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for AgentActivity {
    type Cols = AgentActivityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AgentActivityCols {
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            last_tool_event: __sdk::__query_builder::Col::new(table_name, "last_tool_event"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AgentActivity`.
///
/// Provides typed access to indexed columns for query building.
pub struct AgentActivityIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<AgentActivity, String>,
}

impl __sdk::__query_builder::HasIxCols for AgentActivity {
    type IxCols = AgentActivityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AgentActivityIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AgentActivity {}
