// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_activity_type::AgentActivity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent_activity`.
///
/// Obtain a handle from the [`AgentActivityTableAccess::agent_activity`] method on [`super::RemoteTables`],
/// like `ctx.db.agent_activity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_activity().on_insert(...)`.
pub struct AgentActivityTableHandle<'ctx> {
    imp: __sdk::TableHandle<AgentActivity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent_activity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentActivityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentActivityTableHandle`], which mediates access to the table `agent_activity`.
    fn agent_activity(&self) -> AgentActivityTableHandle<'_>;
}

impl AgentActivityTableAccess for super::RemoteTables {
    fn agent_activity(&self) -> AgentActivityTableHandle<'_> {
        AgentActivityTableHandle {
            imp: self.imp.get_table::<AgentActivity>("agent_activity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentActivityInsertCallbackId(__sdk::CallbackId);
pub struct AgentActivityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentActivityTableHandle<'ctx> {
    type Row = AgentActivity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AgentActivity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentActivityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentActivityInsertCallbackId {
        AgentActivityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentActivityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentActivityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentActivityDeleteCallbackId {
        AgentActivityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentActivityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentActivityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentActivityTableHandle<'ctx> {
    type UpdateCallbackId = AgentActivityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentActivityUpdateCallbackId {
        AgentActivityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentActivityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `agent_activity`,
/// which allows point queries on the field of the same name
/// via the [`AgentActivityAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent_activity().agent_id().find(...)`.
pub struct AgentActivityAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AgentActivity, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentActivityTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `agent_activity`.
    pub fn agent_id(&self) -> AgentActivityAgentIdUnique<'ctx> {
        AgentActivityAgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentActivityAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<AgentActivity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AgentActivity>("agent_activity");
    _table.add_unique_constraint::<String>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AgentActivity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AgentActivity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AgentActivity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agent_activityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AgentActivity`.
    fn agent_activity(&self) -> __sdk::__query_builder::Table<AgentActivity>;
}

impl agent_activityQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent_activity(&self) -> __sdk::__query_builder::Table<AgentActivity> {
        __sdk::__query_builder::Table::new("agent_activity")
    }
}
