// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendToNoteArgs {
    pub path: String,
    pub content: String,
}

impl From<AppendToNoteArgs> for super::Reducer {
    fn from(args: AppendToNoteArgs) -> Self {
        Self::AppendToNote {
            path: args.path,
            content: args.content,
        }
    }
}

impl __sdk::InModule for AppendToNoteArgs {
    type Module = super::RemoteModule;
}

pub struct AppendToNoteCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_to_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_to_note {
    /// Request that the remote module invoke the reducer `append_to_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_append_to_note`] callbacks.
    fn append_to_note(&self, path: String, content: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `append_to_note`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AppendToNoteCallbackId`] can be passed to [`Self::remove_on_append_to_note`]
    /// to cancel the callback.
    fn on_append_to_note(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AppendToNoteCallbackId;
    /// Cancel a callback previously registered by [`Self::on_append_to_note`],
    /// causing it not to run in the future.
    fn remove_on_append_to_note(&self, callback: AppendToNoteCallbackId);
}

impl append_to_note for super::RemoteReducers {
    fn append_to_note(&self, path: String, content: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("append_to_note", AppendToNoteArgs { path, content })
    }
    fn on_append_to_note(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AppendToNoteCallbackId {
        AppendToNoteCallbackId(self.imp.on_reducer(
            "append_to_note",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AppendToNote { path, content },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, path, content)
            }),
        ))
    }
    fn remove_on_append_to_note(&self, callback: AppendToNoteCallbackId) {
        self.imp.remove_on_reducer("append_to_note", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `append_to_note`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_append_to_note {
    /// Set the call-reducer flags for the reducer `append_to_note` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn append_to_note(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_append_to_note for super::SetReducerFlags {
    fn append_to_note(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("append_to_note", flags);
    }
}
