// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::call_session_type::CallSession;
use super::call_state_type::CallState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `call_session`.
///
/// Obtain a handle from the [`CallSessionTableAccess::call_session`] method on [`super::RemoteTables`],
/// like `ctx.db.call_session()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.call_session().on_insert(...)`.
pub struct CallSessionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CallSession>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `call_session`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CallSessionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CallSessionTableHandle`], which mediates access to the table `call_session`.
    fn call_session(&self) -> CallSessionTableHandle<'_>;
}

impl CallSessionTableAccess for super::RemoteTables {
    fn call_session(&self) -> CallSessionTableHandle<'_> {
        CallSessionTableHandle {
            imp: self.imp.get_table::<CallSession>("call_session"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CallSessionInsertCallbackId(__sdk::CallbackId);
pub struct CallSessionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CallSessionTableHandle<'ctx> {
    type Row = CallSession;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CallSession> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CallSessionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CallSessionInsertCallbackId {
        CallSessionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CallSessionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CallSessionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CallSessionDeleteCallbackId {
        CallSessionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CallSessionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CallSessionUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CallSessionTableHandle<'ctx> {
    type UpdateCallbackId = CallSessionUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CallSessionUpdateCallbackId {
        CallSessionUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CallSessionUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `agent_id` unique index on the table `call_session`,
/// which allows point queries on the field of the same name
/// via the [`CallSessionAgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.call_session().agent_id().find(...)`.
pub struct CallSessionAgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CallSession, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CallSessionTableHandle<'ctx> {
    /// Get a handle on the `agent_id` unique index on the table `call_session`.
    pub fn agent_id(&self) -> CallSessionAgentIdUnique<'ctx> {
        CallSessionAgentIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("agent_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CallSessionAgentIdUnique<'ctx> {
    /// Find the subscribed row whose `agent_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CallSession> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CallSession>("call_session");
    _table.add_unique_constraint::<u64>("agent_id", |row| &row.agent_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CallSession>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CallSession>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CallSession`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait call_sessionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CallSession`.
    fn call_session(&self) -> __sdk::__query_builder::Table<CallSession>;
}

impl call_sessionQueryTableAccess for __sdk::QueryTableAccessor {
    fn call_session(&self) -> __sdk::__query_builder::Table<CallSession> {
        __sdk::__query_builder::Table::new("call_session")
    }
}
