// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ChannelConfig {
    pub id: u32,
    pub a_2_a_enabled: bool,
    pub a_2_a_cooldown_secs: u32,
    pub a_2_a_hourly_limit: u32,
    pub a_2_a_max_hops: u32,
}

impl __sdk::InModule for ChannelConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ChannelConfig`.
///
/// Provides typed access to columns for query building.
pub struct ChannelConfigCols {
    pub id: __sdk::__query_builder::Col<ChannelConfig, u32>,
    pub a_2_a_enabled: __sdk::__query_builder::Col<ChannelConfig, bool>,
    pub a_2_a_cooldown_secs: __sdk::__query_builder::Col<ChannelConfig, u32>,
    pub a_2_a_hourly_limit: __sdk::__query_builder::Col<ChannelConfig, u32>,
    pub a_2_a_max_hops: __sdk::__query_builder::Col<ChannelConfig, u32>,
}

impl __sdk::__query_builder::HasCols for ChannelConfig {
    type Cols = ChannelConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ChannelConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            a_2_a_enabled: __sdk::__query_builder::Col::new(table_name, "a_2_a_enabled"),
            a_2_a_cooldown_secs: __sdk::__query_builder::Col::new(
                table_name,
                "a_2_a_cooldown_secs",
            ),
            a_2_a_hourly_limit: __sdk::__query_builder::Col::new(table_name, "a_2_a_hourly_limit"),
            a_2_a_max_hops: __sdk::__query_builder::Col::new(table_name, "a_2_a_max_hops"),
        }
    }
}

/// Indexed column accessor struct for the table `ChannelConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct ChannelConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<ChannelConfig, u32>,
}

impl __sdk::__query_builder::HasIxCols for ChannelConfig {
    type IxCols = ChannelConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ChannelConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ChannelConfig {}
