// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteFileArgs {
    pub id: String,
}

impl From<DeleteFileArgs> for super::Reducer {
    fn from(args: DeleteFileArgs) -> Self {
        Self::DeleteFile { id: args.id }
    }
}

impl __sdk::InModule for DeleteFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_file {
    /// Request that the remote module invoke the reducer `delete_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_file:delete_file_then`] to run a callback after the reducer completes.
    fn delete_file(&self, id: String) -> __sdk::Result<()> {
        self.delete_file_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_file` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_file_then(
        &self,
        id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_file for super::RemoteReducers {
    fn delete_file_then(
        &self,
        id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteFileArgs { id }, callback)
    }
}
