// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EditMessageArgs {
    pub id: String,
    pub text: String,
}

impl From<EditMessageArgs> for super::Reducer {
    fn from(args: EditMessageArgs) -> Self {
        Self::EditMessage {
            id: args.id,
            text: args.text,
        }
    }
}

impl __sdk::InModule for EditMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `edit_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait edit_message {
    /// Request that the remote module invoke the reducer `edit_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`edit_message:edit_message_then`] to run a callback after the reducer completes.
    fn edit_message(&self, id: String, text: String) -> __sdk::Result<()> {
        self.edit_message_then(id, text, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `edit_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn edit_message_then(
        &self,
        id: String,
        text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl edit_message for super::RemoteReducers {
    fn edit_message_then(
        &self,
        id: String,
        text: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EditMessageArgs { id, text }, callback)
    }
}
