// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FindReplaceInNoteArgs {
    pub path: String,
    pub old_text: String,
    pub new_text: String,
    pub replace_all: bool,
}

impl From<FindReplaceInNoteArgs> for super::Reducer {
    fn from(args: FindReplaceInNoteArgs) -> Self {
        Self::FindReplaceInNote {
            path: args.path,
            old_text: args.old_text,
            new_text: args.new_text,
            replace_all: args.replace_all,
        }
    }
}

impl __sdk::InModule for FindReplaceInNoteArgs {
    type Module = super::RemoteModule;
}

pub struct FindReplaceInNoteCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `find_replace_in_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait find_replace_in_note {
    /// Request that the remote module invoke the reducer `find_replace_in_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_find_replace_in_note`] callbacks.
    fn find_replace_in_note(
        &self,
        path: String,
        old_text: String,
        new_text: String,
        replace_all: bool,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `find_replace_in_note`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`FindReplaceInNoteCallbackId`] can be passed to [`Self::remove_on_find_replace_in_note`]
    /// to cancel the callback.
    fn on_find_replace_in_note(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &bool)
            + Send
            + 'static,
    ) -> FindReplaceInNoteCallbackId;
    /// Cancel a callback previously registered by [`Self::on_find_replace_in_note`],
    /// causing it not to run in the future.
    fn remove_on_find_replace_in_note(&self, callback: FindReplaceInNoteCallbackId);
}

impl find_replace_in_note for super::RemoteReducers {
    fn find_replace_in_note(
        &self,
        path: String,
        old_text: String,
        new_text: String,
        replace_all: bool,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "find_replace_in_note",
            FindReplaceInNoteArgs {
                path,
                old_text,
                new_text,
                replace_all,
            },
        )
    }
    fn on_find_replace_in_note(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String, &String, &bool)
            + Send
            + 'static,
    ) -> FindReplaceInNoteCallbackId {
        FindReplaceInNoteCallbackId(self.imp.on_reducer(
            "find_replace_in_note",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::FindReplaceInNote {
                                    path,
                                    old_text,
                                    new_text,
                                    replace_all,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, path, old_text, new_text, replace_all)
            }),
        ))
    }
    fn remove_on_find_replace_in_note(&self, callback: FindReplaceInNoteCallbackId) {
        self.imp
            .remove_on_reducer("find_replace_in_note", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `find_replace_in_note`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_find_replace_in_note {
    /// Set the call-reducer flags for the reducer `find_replace_in_note` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn find_replace_in_note(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_find_replace_in_note for super::SetReducerFlags {
    fn find_replace_in_note(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("find_replace_in_note", flags);
    }
}
