// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct FindReplaceInFileArgs {
    pub path: String,
    pub old_text: String,
    pub new_text: String,
    pub replace_all: bool,
}

impl From<FindReplaceInFileArgs> for super::Reducer {
    fn from(args: FindReplaceInFileArgs) -> Self {
        Self::FindReplaceInFile {
            path: args.path,
            old_text: args.old_text,
            new_text: args.new_text,
            replace_all: args.replace_all,
        }
    }
}

impl __sdk::InModule for FindReplaceInFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `find_replace_in_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait find_replace_in_file {
    /// Request that the remote module invoke the reducer `find_replace_in_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`find_replace_in_file:find_replace_in_file_then`] to run a callback after the reducer completes.
    fn find_replace_in_file(
        &self,
        path: String,
        old_text: String,
        new_text: String,
        replace_all: bool,
    ) -> __sdk::Result<()> {
        self.find_replace_in_file_then(path, old_text, new_text, replace_all, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `find_replace_in_file` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn find_replace_in_file_then(
        &self,
        path: String,
        old_text: String,
        new_text: String,
        replace_all: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl find_replace_in_file for super::RemoteReducers {
    fn find_replace_in_file_then(
        &self,
        path: String,
        old_text: String,
        new_text: String,
        replace_all: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            FindReplaceInFileArgs {
                path,
                old_text,
                new_text,
                replace_all,
            },
            callback,
        )
    }
}
