// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetRecentNotesArgs {
    pub limit: u32,
}

impl From<GetRecentNotesArgs> for super::Reducer {
    fn from(args: GetRecentNotesArgs) -> Self {
        Self::GetRecentNotes { limit: args.limit }
    }
}

impl __sdk::InModule for GetRecentNotesArgs {
    type Module = super::RemoteModule;
}

pub struct GetRecentNotesCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_recent_notes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_recent_notes {
    /// Request that the remote module invoke the reducer `get_recent_notes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_get_recent_notes`] callbacks.
    fn get_recent_notes(&self, limit: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `get_recent_notes`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`GetRecentNotesCallbackId`] can be passed to [`Self::remove_on_get_recent_notes`]
    /// to cancel the callback.
    fn on_get_recent_notes(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> GetRecentNotesCallbackId;
    /// Cancel a callback previously registered by [`Self::on_get_recent_notes`],
    /// causing it not to run in the future.
    fn remove_on_get_recent_notes(&self, callback: GetRecentNotesCallbackId);
}

impl get_recent_notes for super::RemoteReducers {
    fn get_recent_notes(&self, limit: u32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("get_recent_notes", GetRecentNotesArgs { limit })
    }
    fn on_get_recent_notes(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u32) + Send + 'static,
    ) -> GetRecentNotesCallbackId {
        GetRecentNotesCallbackId(self.imp.on_reducer(
            "get_recent_notes",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::GetRecentNotes { limit },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, limit)
            }),
        ))
    }
    fn remove_on_get_recent_notes(&self, callback: GetRecentNotesCallbackId) {
        self.imp.remove_on_reducer("get_recent_notes", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `get_recent_notes`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_get_recent_notes {
    /// Set the call-reducer flags for the reducer `get_recent_notes` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn get_recent_notes(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_get_recent_notes for super::SetReducerFlags {
    fn get_recent_notes(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("get_recent_notes", flags);
    }
}
