// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetRecentFilesArgs {
    pub limit: u32,
}

impl From<GetRecentFilesArgs> for super::Reducer {
    fn from(args: GetRecentFilesArgs) -> Self {
        Self::GetRecentFiles { limit: args.limit }
    }
}

impl __sdk::InModule for GetRecentFilesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_recent_files`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_recent_files {
    /// Request that the remote module invoke the reducer `get_recent_files` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_recent_files:get_recent_files_then`] to run a callback after the reducer completes.
    fn get_recent_files(&self, limit: u32) -> __sdk::Result<()> {
        self.get_recent_files_then(limit, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_recent_files` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_recent_files_then(
        &self,
        limit: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_recent_files for super::RemoteReducers {
    fn get_recent_files_then(
        &self,
        limit: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetRecentFilesArgs { limit }, callback)
    }
}
