// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Message {
    pub id: String,
    pub session_id: String,
    pub role: String,
    pub text: String,
    pub source: String,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for Message {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Message`.
///
/// Provides typed access to columns for query building.
pub struct MessageCols {
    pub id: __sdk::__query_builder::Col<Message, String>,
    pub session_id: __sdk::__query_builder::Col<Message, String>,
    pub role: __sdk::__query_builder::Col<Message, String>,
    pub text: __sdk::__query_builder::Col<Message, String>,
    pub source: __sdk::__query_builder::Col<Message, String>,
    pub created_at: __sdk::__query_builder::Col<Message, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Message {
    type Cols = MessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            role: __sdk::__query_builder::Col::new(table_name, "role"),
            text: __sdk::__query_builder::Col::new(table_name, "text"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Message`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageIxCols {
    pub created_at: __sdk::__query_builder::IxCol<Message, __sdk::Timestamp>,
    pub id: __sdk::__query_builder::IxCol<Message, String>,
    pub session_id: __sdk::__query_builder::IxCol<Message, String>,
}

impl __sdk::__query_builder::HasIxCols for Message {
    type IxCols = MessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageIxCols {
            created_at: __sdk::__query_builder::IxCol::new(table_name, "created_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Message {}
