// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MessageImage {
    pub message_id: String,
    pub bytes: Vec<u8>,
}

impl __sdk::InModule for MessageImage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MessageImage`.
///
/// Provides typed access to columns for query building.
pub struct MessageImageCols {
    pub message_id: __sdk::__query_builder::Col<MessageImage, String>,
    pub bytes: __sdk::__query_builder::Col<MessageImage, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for MessageImage {
    type Cols = MessageImageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageImageCols {
            message_id: __sdk::__query_builder::Col::new(table_name, "message_id"),
            bytes: __sdk::__query_builder::Col::new(table_name, "bytes"),
        }
    }
}

/// Indexed column accessor struct for the table `MessageImage`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageImageIxCols {
    pub message_id: __sdk::__query_builder::IxCol<MessageImage, String>,
}

impl __sdk::__query_builder::HasIxCols for MessageImage {
    type IxCols = MessageImageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageImageIxCols {
            message_id: __sdk::__query_builder::IxCol::new(table_name, "message_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MessageImage {}
