// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod accept_call_reducer;
pub mod append_to_note_reducer;
pub mod audio_frame_table;
pub mod audio_frame_type;
pub mod call_session_table;
pub mod call_session_type;
pub mod call_state_type;
pub mod clear_all_reducer;
pub mod clear_all_sessions_reducer;
pub mod connected_user_table;
pub mod connected_user_type;
pub mod create_folder_reducer;
pub mod create_note_reducer;
pub mod delete_folder_reducer;
pub mod delete_note_reducer;
pub mod delete_session_reducer;
pub mod edit_message_reducer;
pub mod end_call_reducer;
pub mod end_session_reducer;
pub mod find_replace_in_note_reducer;
pub mod folder_table;
pub mod folder_type;
pub mod get_recent_notes_reducer;
pub mod heartbeat_reducer;
pub mod message_image_table;
pub mod message_image_type;
pub mod message_table;
pub mod message_type;
pub mod move_folder_reducer;
pub mod move_note_reducer;
pub mod note_table;
pub mod note_type;
pub mod permission_request_table;
pub mod permission_request_type;
pub mod prepend_to_note_reducer;
pub mod push_context_usage_reducer;
pub mod push_image_reducer;
pub mod push_message_reducer;
pub mod push_status_reducer;
pub mod push_tool_event_reducer;
pub mod register_session_reducer;
pub mod rename_note_reducer;
pub mod request_call_reducer;
pub mod request_permission_reducer;
pub mod resolve_permission_reducer;
pub mod send_audio_frame_reducer;
pub mod send_video_frame_reducer;
pub mod session_activity_table;
pub mod session_activity_type;
pub mod session_table;
pub mod session_type;
pub mod set_display_name_reducer;
pub mod sweep_old_messages_reducer;
pub mod tool_event_table;
pub mod tool_event_type;
pub mod update_note_content_reducer;
pub mod update_note_path_reducer;
pub mod upsert_folder_reducer;
pub mod upsert_note_reducer;
pub mod user_profile_table;
pub mod user_profile_type;
pub mod video_frame_table;
pub mod video_frame_type;

pub use accept_call_reducer::accept_call;
pub use append_to_note_reducer::append_to_note;
pub use audio_frame_table::*;
pub use audio_frame_type::AudioFrame;
pub use call_session_table::*;
pub use call_session_type::CallSession;
pub use call_state_type::CallState;
pub use clear_all_reducer::clear_all;
pub use clear_all_sessions_reducer::clear_all_sessions;
pub use connected_user_table::*;
pub use connected_user_type::ConnectedUser;
pub use create_folder_reducer::create_folder;
pub use create_note_reducer::create_note;
pub use delete_folder_reducer::delete_folder;
pub use delete_note_reducer::delete_note;
pub use delete_session_reducer::delete_session;
pub use edit_message_reducer::edit_message;
pub use end_call_reducer::end_call;
pub use end_session_reducer::end_session;
pub use find_replace_in_note_reducer::find_replace_in_note;
pub use folder_table::*;
pub use folder_type::Folder;
pub use get_recent_notes_reducer::get_recent_notes;
pub use heartbeat_reducer::heartbeat;
pub use message_image_table::*;
pub use message_image_type::MessageImage;
pub use message_table::*;
pub use message_type::Message;
pub use move_folder_reducer::move_folder;
pub use move_note_reducer::move_note;
pub use note_table::*;
pub use note_type::Note;
pub use permission_request_table::*;
pub use permission_request_type::PermissionRequest;
pub use prepend_to_note_reducer::prepend_to_note;
pub use push_context_usage_reducer::push_context_usage;
pub use push_image_reducer::push_image;
pub use push_message_reducer::push_message;
pub use push_status_reducer::push_status;
pub use push_tool_event_reducer::push_tool_event;
pub use register_session_reducer::register_session;
pub use rename_note_reducer::rename_note;
pub use request_call_reducer::request_call;
pub use request_permission_reducer::request_permission;
pub use resolve_permission_reducer::resolve_permission;
pub use send_audio_frame_reducer::send_audio_frame;
pub use send_video_frame_reducer::send_video_frame;
pub use session_activity_table::*;
pub use session_activity_type::SessionActivity;
pub use session_table::*;
pub use session_type::Session;
pub use set_display_name_reducer::set_display_name;
pub use sweep_old_messages_reducer::sweep_old_messages;
pub use tool_event_table::*;
pub use tool_event_type::ToolEvent;
pub use update_note_content_reducer::update_note_content;
pub use update_note_path_reducer::update_note_path;
pub use upsert_folder_reducer::upsert_folder;
pub use upsert_note_reducer::upsert_note;
pub use user_profile_table::*;
pub use user_profile_type::UserProfile;
pub use video_frame_table::*;
pub use video_frame_type::VideoFrame;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AcceptCall {
        session_id: u64,
    },
    AppendToNote {
        path: String,
        content: String,
    },
    ClearAll,
    ClearAllSessions,
    CreateFolder {
        path: String,
        name: String,
        depth: u32,
    },
    CreateNote {
        id: String,
        path: String,
        name: String,
        content: String,
        folder_path: String,
        depth: u32,
        extension: String,
        kind: String,
        size: u64,
        created_time: u64,
        modified_time: u64,
    },
    DeleteFolder {
        path: String,
    },
    DeleteNote {
        id: String,
    },
    DeleteSession {
        session_id: String,
    },
    EditMessage {
        id: String,
        text: String,
    },
    EndCall {
        session_id: u64,
    },
    EndSession {
        session_id: String,
    },
    FindReplaceInNote {
        path: String,
        old_text: String,
        new_text: String,
        replace_all: bool,
    },
    GetRecentNotes {
        limit: u32,
    },
    Heartbeat {
        session_id: String,
    },
    MoveFolder {
        old_path: String,
        new_path: String,
    },
    MoveNote {
        old_path: String,
        new_path: String,
    },
    PrependToNote {
        path: String,
        content: String,
    },
    PushContextUsage {
        session_id: String,
        used: u64,
        window: u64,
    },
    PushImage {
        id: String,
        session_id: String,
        caption: String,
        bytes: Vec<u8>,
    },
    PushMessage {
        id: String,
        session_id: String,
        role: String,
        text: String,
        source: String,
    },
    PushStatus {
        session_id: String,
        state: String,
    },
    PushToolEvent {
        id: String,
        session_id: String,
        tool: String,
        detail: String,
    },
    RegisterSession {
        id: String,
        base_name: String,
        host: String,
        client_id: String,
    },
    RenameNote {
        id: String,
        new_path: String,
    },
    RequestCall {
        callee: __sdk::Identity,
    },
    RequestPermission {
        id: String,
        session_id: String,
        tool: String,
        input: String,
    },
    ResolvePermission {
        id: String,
        status: String,
    },
    SendAudioFrame {
        session_id: u64,
        seq: u32,
        pcm: Vec<u8>,
    },
    SendVideoFrame {
        session_id: u64,
        seq: u32,
        codec: u8,
        is_keyframe: bool,
        data: Vec<u8>,
    },
    SetDisplayName {
        name: String,
    },
    SweepOldMessages,
    UpdateNoteContent {
        id: String,
        content: String,
        size: u64,
        modified_time: u64,
    },
    UpdateNotePath {
        id: String,
        new_path: String,
    },
    UpsertFolder {
        path: String,
        name: String,
        depth: u32,
    },
    UpsertNote {
        id: String,
        path: String,
        name: String,
        content: String,
        folder_path: String,
        depth: u32,
        extension: String,
        kind: String,
        size: u64,
        created_time: u64,
        modified_time: u64,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AcceptCall { .. } => "accept_call",
            Reducer::AppendToNote { .. } => "append_to_note",
            Reducer::ClearAll => "clear_all",
            Reducer::ClearAllSessions => "clear_all_sessions",
            Reducer::CreateFolder { .. } => "create_folder",
            Reducer::CreateNote { .. } => "create_note",
            Reducer::DeleteFolder { .. } => "delete_folder",
            Reducer::DeleteNote { .. } => "delete_note",
            Reducer::DeleteSession { .. } => "delete_session",
            Reducer::EditMessage { .. } => "edit_message",
            Reducer::EndCall { .. } => "end_call",
            Reducer::EndSession { .. } => "end_session",
            Reducer::FindReplaceInNote { .. } => "find_replace_in_note",
            Reducer::GetRecentNotes { .. } => "get_recent_notes",
            Reducer::Heartbeat { .. } => "heartbeat",
            Reducer::MoveFolder { .. } => "move_folder",
            Reducer::MoveNote { .. } => "move_note",
            Reducer::PrependToNote { .. } => "prepend_to_note",
            Reducer::PushContextUsage { .. } => "push_context_usage",
            Reducer::PushImage { .. } => "push_image",
            Reducer::PushMessage { .. } => "push_message",
            Reducer::PushStatus { .. } => "push_status",
            Reducer::PushToolEvent { .. } => "push_tool_event",
            Reducer::RegisterSession { .. } => "register_session",
            Reducer::RenameNote { .. } => "rename_note",
            Reducer::RequestCall { .. } => "request_call",
            Reducer::RequestPermission { .. } => "request_permission",
            Reducer::ResolvePermission { .. } => "resolve_permission",
            Reducer::SendAudioFrame { .. } => "send_audio_frame",
            Reducer::SendVideoFrame { .. } => "send_video_frame",
            Reducer::SetDisplayName { .. } => "set_display_name",
            Reducer::SweepOldMessages => "sweep_old_messages",
            Reducer::UpdateNoteContent { .. } => "update_note_content",
            Reducer::UpdateNotePath { .. } => "update_note_path",
            Reducer::UpsertFolder { .. } => "upsert_folder",
            Reducer::UpsertNote { .. } => "upsert_note",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
            Reducer::AcceptCall { session_id } => {
                __sats::bsatn::to_vec(&accept_call_reducer::AcceptCallArgs {
                    session_id: session_id.clone(),
                })
            }
            Reducer::AppendToNote { path, content } => {
                __sats::bsatn::to_vec(&append_to_note_reducer::AppendToNoteArgs {
                    path: path.clone(),
                    content: content.clone(),
                })
            }
            Reducer::ClearAll => __sats::bsatn::to_vec(&clear_all_reducer::ClearAllArgs {}),
            Reducer::ClearAllSessions => {
                __sats::bsatn::to_vec(&clear_all_sessions_reducer::ClearAllSessionsArgs {})
            }
            Reducer::CreateFolder { path, name, depth } => {
                __sats::bsatn::to_vec(&create_folder_reducer::CreateFolderArgs {
                    path: path.clone(),
                    name: name.clone(),
                    depth: depth.clone(),
                })
            }
            Reducer::CreateNote {
                id,
                path,
                name,
                content,
                folder_path,
                depth,
                extension,
                kind,
                size,
                created_time,
                modified_time,
            } => __sats::bsatn::to_vec(&create_note_reducer::CreateNoteArgs {
                id: id.clone(),
                path: path.clone(),
                name: name.clone(),
                content: content.clone(),
                folder_path: folder_path.clone(),
                depth: depth.clone(),
                extension: extension.clone(),
                kind: kind.clone(),
                size: size.clone(),
                created_time: created_time.clone(),
                modified_time: modified_time.clone(),
            }),
            Reducer::DeleteFolder { path } => {
                __sats::bsatn::to_vec(&delete_folder_reducer::DeleteFolderArgs {
                    path: path.clone(),
                })
            }
            Reducer::DeleteNote { id } => {
                __sats::bsatn::to_vec(&delete_note_reducer::DeleteNoteArgs { id: id.clone() })
            }
            Reducer::DeleteSession { session_id } => {
                __sats::bsatn::to_vec(&delete_session_reducer::DeleteSessionArgs {
                    session_id: session_id.clone(),
                })
            }
            Reducer::EditMessage { id, text } => {
                __sats::bsatn::to_vec(&edit_message_reducer::EditMessageArgs {
                    id: id.clone(),
                    text: text.clone(),
                })
            }
            Reducer::EndCall { session_id } => {
                __sats::bsatn::to_vec(&end_call_reducer::EndCallArgs {
                    session_id: session_id.clone(),
                })
            }
            Reducer::EndSession { session_id } => {
                __sats::bsatn::to_vec(&end_session_reducer::EndSessionArgs {
                    session_id: session_id.clone(),
                })
            }
            Reducer::FindReplaceInNote {
                path,
                old_text,
                new_text,
                replace_all,
            } => __sats::bsatn::to_vec(&find_replace_in_note_reducer::FindReplaceInNoteArgs {
                path: path.clone(),
                old_text: old_text.clone(),
                new_text: new_text.clone(),
                replace_all: replace_all.clone(),
            }),
            Reducer::GetRecentNotes { limit } => {
                __sats::bsatn::to_vec(&get_recent_notes_reducer::GetRecentNotesArgs {
                    limit: limit.clone(),
                })
            }
            Reducer::Heartbeat { session_id } => {
                __sats::bsatn::to_vec(&heartbeat_reducer::HeartbeatArgs {
                    session_id: session_id.clone(),
                })
            }
            Reducer::MoveFolder { old_path, new_path } => {
                __sats::bsatn::to_vec(&move_folder_reducer::MoveFolderArgs {
                    old_path: old_path.clone(),
                    new_path: new_path.clone(),
                })
            }
            Reducer::MoveNote { old_path, new_path } => {
                __sats::bsatn::to_vec(&move_note_reducer::MoveNoteArgs {
                    old_path: old_path.clone(),
                    new_path: new_path.clone(),
                })
            }
            Reducer::PrependToNote { path, content } => {
                __sats::bsatn::to_vec(&prepend_to_note_reducer::PrependToNoteArgs {
                    path: path.clone(),
                    content: content.clone(),
                })
            }
            Reducer::PushContextUsage {
                session_id,
                used,
                window,
            } => __sats::bsatn::to_vec(&push_context_usage_reducer::PushContextUsageArgs {
                session_id: session_id.clone(),
                used: used.clone(),
                window: window.clone(),
            }),
            Reducer::PushImage {
                id,
                session_id,
                caption,
                bytes,
            } => __sats::bsatn::to_vec(&push_image_reducer::PushImageArgs {
                id: id.clone(),
                session_id: session_id.clone(),
                caption: caption.clone(),
                bytes: bytes.clone(),
            }),
            Reducer::PushMessage {
                id,
                session_id,
                role,
                text,
                source,
            } => __sats::bsatn::to_vec(&push_message_reducer::PushMessageArgs {
                id: id.clone(),
                session_id: session_id.clone(),
                role: role.clone(),
                text: text.clone(),
                source: source.clone(),
            }),
            Reducer::PushStatus { session_id, state } => {
                __sats::bsatn::to_vec(&push_status_reducer::PushStatusArgs {
                    session_id: session_id.clone(),
                    state: state.clone(),
                })
            }
            Reducer::PushToolEvent {
                id,
                session_id,
                tool,
                detail,
            } => __sats::bsatn::to_vec(&push_tool_event_reducer::PushToolEventArgs {
                id: id.clone(),
                session_id: session_id.clone(),
                tool: tool.clone(),
                detail: detail.clone(),
            }),
            Reducer::RegisterSession {
                id,
                base_name,
                host,
                client_id,
            } => __sats::bsatn::to_vec(&register_session_reducer::RegisterSessionArgs {
                id: id.clone(),
                base_name: base_name.clone(),
                host: host.clone(),
                client_id: client_id.clone(),
            }),
            Reducer::RenameNote { id, new_path } => {
                __sats::bsatn::to_vec(&rename_note_reducer::RenameNoteArgs {
                    id: id.clone(),
                    new_path: new_path.clone(),
                })
            }
            Reducer::RequestCall { callee } => {
                __sats::bsatn::to_vec(&request_call_reducer::RequestCallArgs {
                    callee: callee.clone(),
                })
            }
            Reducer::RequestPermission {
                id,
                session_id,
                tool,
                input,
            } => __sats::bsatn::to_vec(&request_permission_reducer::RequestPermissionArgs {
                id: id.clone(),
                session_id: session_id.clone(),
                tool: tool.clone(),
                input: input.clone(),
            }),
            Reducer::ResolvePermission { id, status } => {
                __sats::bsatn::to_vec(&resolve_permission_reducer::ResolvePermissionArgs {
                    id: id.clone(),
                    status: status.clone(),
                })
            }
            Reducer::SendAudioFrame {
                session_id,
                seq,
                pcm,
            } => __sats::bsatn::to_vec(&send_audio_frame_reducer::SendAudioFrameArgs {
                session_id: session_id.clone(),
                seq: seq.clone(),
                pcm: pcm.clone(),
            }),
            Reducer::SendVideoFrame {
                session_id,
                seq,
                codec,
                is_keyframe,
                data,
            } => __sats::bsatn::to_vec(&send_video_frame_reducer::SendVideoFrameArgs {
                session_id: session_id.clone(),
                seq: seq.clone(),
                codec: codec.clone(),
                is_keyframe: is_keyframe.clone(),
                data: data.clone(),
            }),
            Reducer::SetDisplayName { name } => {
                __sats::bsatn::to_vec(&set_display_name_reducer::SetDisplayNameArgs {
                    name: name.clone(),
                })
            }
            Reducer::SweepOldMessages => {
                __sats::bsatn::to_vec(&sweep_old_messages_reducer::SweepOldMessagesArgs {})
            }
            Reducer::UpdateNoteContent {
                id,
                content,
                size,
                modified_time,
            } => __sats::bsatn::to_vec(&update_note_content_reducer::UpdateNoteContentArgs {
                id: id.clone(),
                content: content.clone(),
                size: size.clone(),
                modified_time: modified_time.clone(),
            }),
            Reducer::UpdateNotePath { id, new_path } => {
                __sats::bsatn::to_vec(&update_note_path_reducer::UpdateNotePathArgs {
                    id: id.clone(),
                    new_path: new_path.clone(),
                })
            }
            Reducer::UpsertFolder { path, name, depth } => {
                __sats::bsatn::to_vec(&upsert_folder_reducer::UpsertFolderArgs {
                    path: path.clone(),
                    name: name.clone(),
                    depth: depth.clone(),
                })
            }
            Reducer::UpsertNote {
                id,
                path,
                name,
                content,
                folder_path,
                depth,
                extension,
                kind,
                size,
                created_time,
                modified_time,
            } => __sats::bsatn::to_vec(&upsert_note_reducer::UpsertNoteArgs {
                id: id.clone(),
                path: path.clone(),
                name: name.clone(),
                content: content.clone(),
                folder_path: folder_path.clone(),
                depth: depth.clone(),
                extension: extension.clone(),
                kind: kind.clone(),
                size: size.clone(),
                created_time: created_time.clone(),
                modified_time: modified_time.clone(),
            }),
            _ => unreachable!(),
        }
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    audio_frame: __sdk::TableUpdate<AudioFrame>,
    call_session: __sdk::TableUpdate<CallSession>,
    connected_user: __sdk::TableUpdate<ConnectedUser>,
    folder: __sdk::TableUpdate<Folder>,
    message: __sdk::TableUpdate<Message>,
    message_image: __sdk::TableUpdate<MessageImage>,
    note: __sdk::TableUpdate<Note>,
    permission_request: __sdk::TableUpdate<PermissionRequest>,
    session: __sdk::TableUpdate<Session>,
    session_activity: __sdk::TableUpdate<SessionActivity>,
    tool_event: __sdk::TableUpdate<ToolEvent>,
    user_profile: __sdk::TableUpdate<UserProfile>,
    video_frame: __sdk::TableUpdate<VideoFrame>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "audio_frame" => db_update
                    .audio_frame
                    .append(audio_frame_table::parse_table_update(table_update)?),
                "call_session" => db_update
                    .call_session
                    .append(call_session_table::parse_table_update(table_update)?),
                "connected_user" => db_update
                    .connected_user
                    .append(connected_user_table::parse_table_update(table_update)?),
                "folder" => db_update
                    .folder
                    .append(folder_table::parse_table_update(table_update)?),
                "message" => db_update
                    .message
                    .append(message_table::parse_table_update(table_update)?),
                "message_image" => db_update
                    .message_image
                    .append(message_image_table::parse_table_update(table_update)?),
                "note" => db_update
                    .note
                    .append(note_table::parse_table_update(table_update)?),
                "permission_request" => db_update
                    .permission_request
                    .append(permission_request_table::parse_table_update(table_update)?),
                "session" => db_update
                    .session
                    .append(session_table::parse_table_update(table_update)?),
                "session_activity" => db_update
                    .session_activity
                    .append(session_activity_table::parse_table_update(table_update)?),
                "tool_event" => db_update
                    .tool_event
                    .append(tool_event_table::parse_table_update(table_update)?),
                "user_profile" => db_update
                    .user_profile
                    .append(user_profile_table::parse_table_update(table_update)?),
                "video_frame" => db_update
                    .video_frame
                    .append(video_frame_table::parse_table_update(table_update)?),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.audio_frame = self.audio_frame.into_event_diff();
        diff.call_session = cache
            .apply_diff_to_table::<CallSession>("call_session", &self.call_session)
            .with_updates_by_pk(|row| &row.session_id);
        diff.connected_user = cache
            .apply_diff_to_table::<ConnectedUser>("connected_user", &self.connected_user)
            .with_updates_by_pk(|row| &row.identity);
        diff.folder = cache
            .apply_diff_to_table::<Folder>("folder", &self.folder)
            .with_updates_by_pk(|row| &row.path);
        diff.message = cache
            .apply_diff_to_table::<Message>("message", &self.message)
            .with_updates_by_pk(|row| &row.id);
        diff.message_image = cache
            .apply_diff_to_table::<MessageImage>("message_image", &self.message_image)
            .with_updates_by_pk(|row| &row.message_id);
        diff.note = cache
            .apply_diff_to_table::<Note>("note", &self.note)
            .with_updates_by_pk(|row| &row.id);
        diff.permission_request = cache
            .apply_diff_to_table::<PermissionRequest>(
                "permission_request",
                &self.permission_request,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.session = cache
            .apply_diff_to_table::<Session>("session", &self.session)
            .with_updates_by_pk(|row| &row.id);
        diff.session_activity = cache
            .apply_diff_to_table::<SessionActivity>("session_activity", &self.session_activity)
            .with_updates_by_pk(|row| &row.session_id);
        diff.tool_event = cache
            .apply_diff_to_table::<ToolEvent>("tool_event", &self.tool_event)
            .with_updates_by_pk(|row| &row.id);
        diff.user_profile = cache
            .apply_diff_to_table::<UserProfile>("user_profile", &self.user_profile)
            .with_updates_by_pk(|row| &row.identity);
        diff.video_frame = self.video_frame.into_event_diff();

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "audio_frame" => db_update
                    .audio_frame
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "call_session" => db_update
                    .call_session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "connected_user" => db_update
                    .connected_user
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "folder" => db_update
                    .folder
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "message_image" => db_update
                    .message_image
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "note" => db_update
                    .note
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "permission_request" => db_update
                    .permission_request
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "session" => db_update
                    .session
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "session_activity" => db_update
                    .session_activity
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "tool_event" => db_update
                    .tool_event
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "user_profile" => db_update
                    .user_profile
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "video_frame" => db_update
                    .video_frame
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "audio_frame" => db_update
                    .audio_frame
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "call_session" => db_update
                    .call_session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "connected_user" => db_update
                    .connected_user
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "folder" => db_update
                    .folder
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message" => db_update
                    .message
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "message_image" => db_update
                    .message_image
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "note" => db_update
                    .note
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "permission_request" => db_update
                    .permission_request
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "session" => db_update
                    .session
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "session_activity" => db_update
                    .session_activity
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "tool_event" => db_update
                    .tool_event
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "user_profile" => db_update
                    .user_profile
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "video_frame" => db_update
                    .video_frame
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    audio_frame: __sdk::TableAppliedDiff<'r, AudioFrame>,
    call_session: __sdk::TableAppliedDiff<'r, CallSession>,
    connected_user: __sdk::TableAppliedDiff<'r, ConnectedUser>,
    folder: __sdk::TableAppliedDiff<'r, Folder>,
    message: __sdk::TableAppliedDiff<'r, Message>,
    message_image: __sdk::TableAppliedDiff<'r, MessageImage>,
    note: __sdk::TableAppliedDiff<'r, Note>,
    permission_request: __sdk::TableAppliedDiff<'r, PermissionRequest>,
    session: __sdk::TableAppliedDiff<'r, Session>,
    session_activity: __sdk::TableAppliedDiff<'r, SessionActivity>,
    tool_event: __sdk::TableAppliedDiff<'r, ToolEvent>,
    user_profile: __sdk::TableAppliedDiff<'r, UserProfile>,
    video_frame: __sdk::TableAppliedDiff<'r, VideoFrame>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<AudioFrame>("audio_frame", &self.audio_frame, event);
        callbacks.invoke_table_row_callbacks::<CallSession>(
            "call_session",
            &self.call_session,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ConnectedUser>(
            "connected_user",
            &self.connected_user,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Folder>("folder", &self.folder, event);
        callbacks.invoke_table_row_callbacks::<Message>("message", &self.message, event);
        callbacks.invoke_table_row_callbacks::<MessageImage>(
            "message_image",
            &self.message_image,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Note>("note", &self.note, event);
        callbacks.invoke_table_row_callbacks::<PermissionRequest>(
            "permission_request",
            &self.permission_request,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Session>("session", &self.session, event);
        callbacks.invoke_table_row_callbacks::<SessionActivity>(
            "session_activity",
            &self.session_activity,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ToolEvent>("tool_event", &self.tool_event, event);
        callbacks.invoke_table_row_callbacks::<UserProfile>(
            "user_profile",
            &self.user_profile,
            event,
        );
        callbacks.invoke_table_row_callbacks::<VideoFrame>("video_frame", &self.video_frame, event);
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        audio_frame_table::register_table(client_cache);
        call_session_table::register_table(client_cache);
        connected_user_table::register_table(client_cache);
        folder_table::register_table(client_cache);
        message_table::register_table(client_cache);
        message_image_table::register_table(client_cache);
        note_table::register_table(client_cache);
        permission_request_table::register_table(client_cache);
        session_table::register_table(client_cache);
        session_activity_table::register_table(client_cache);
        tool_event_table::register_table(client_cache);
        user_profile_table::register_table(client_cache);
        video_frame_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "audio_frame",
        "call_session",
        "connected_user",
        "folder",
        "message",
        "message_image",
        "note",
        "permission_request",
        "session",
        "session_activity",
        "tool_event",
        "user_profile",
        "video_frame",
    ];
}
