// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveNoteArgs {
    pub old_path: String,
    pub new_path: String,
}

impl From<MoveNoteArgs> for super::Reducer {
    fn from(args: MoveNoteArgs) -> Self {
        Self::MoveNote {
            old_path: args.old_path,
            new_path: args.new_path,
        }
    }
}

impl __sdk::InModule for MoveNoteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_note {
    /// Request that the remote module invoke the reducer `move_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`move_note:move_note_then`] to run a callback after the reducer completes.
    fn move_note(&self, old_path: String, new_path: String) -> __sdk::Result<()> {
        self.move_note_then(old_path, new_path, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `move_note` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn move_note_then(
        &self,
        old_path: String,
        new_path: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl move_note for super::RemoteReducers {
    fn move_note_then(
        &self,
        old_path: String,
        new_path: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(MoveNoteArgs { old_path, new_path }, callback)
    }
}
