// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::permission_request_type::PermissionRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `permission_request`.
///
/// Obtain a handle from the [`PermissionRequestTableAccess::permission_request`] method on [`super::RemoteTables`],
/// like `ctx.db.permission_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.permission_request().on_insert(...)`.
pub struct PermissionRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<PermissionRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `permission_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PermissionRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PermissionRequestTableHandle`], which mediates access to the table `permission_request`.
    fn permission_request(&self) -> PermissionRequestTableHandle<'_>;
}

impl PermissionRequestTableAccess for super::RemoteTables {
    fn permission_request(&self) -> PermissionRequestTableHandle<'_> {
        PermissionRequestTableHandle {
            imp: self
                .imp
                .get_table::<PermissionRequest>("permission_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PermissionRequestInsertCallbackId(__sdk::CallbackId);
pub struct PermissionRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PermissionRequestTableHandle<'ctx> {
    type Row = PermissionRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PermissionRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PermissionRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PermissionRequestInsertCallbackId {
        PermissionRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PermissionRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PermissionRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PermissionRequestDeleteCallbackId {
        PermissionRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PermissionRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct PermissionRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PermissionRequestTableHandle<'ctx> {
    type UpdateCallbackId = PermissionRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PermissionRequestUpdateCallbackId {
        PermissionRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PermissionRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `permission_request`,
/// which allows point queries on the field of the same name
/// via the [`PermissionRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.permission_request().id().find(...)`.
pub struct PermissionRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PermissionRequest, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PermissionRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `permission_request`.
    pub fn id(&self) -> PermissionRequestIdUnique<'ctx> {
        PermissionRequestIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PermissionRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<PermissionRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PermissionRequest>("permission_request");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PermissionRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PermissionRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PermissionRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait permission_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PermissionRequest`.
    fn permission_request(&self) -> __sdk::__query_builder::Table<PermissionRequest>;
}

impl permission_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn permission_request(&self) -> __sdk::__query_builder::Table<PermissionRequest> {
        __sdk::__query_builder::Table::new("permission_request")
    }
}
