// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PrependToNoteArgs {
    pub path: String,
    pub content: String,
}

impl From<PrependToNoteArgs> for super::Reducer {
    fn from(args: PrependToNoteArgs) -> Self {
        Self::PrependToNote {
            path: args.path,
            content: args.content,
        }
    }
}

impl __sdk::InModule for PrependToNoteArgs {
    type Module = super::RemoteModule;
}

pub struct PrependToNoteCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `prepend_to_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait prepend_to_note {
    /// Request that the remote module invoke the reducer `prepend_to_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_prepend_to_note`] callbacks.
    fn prepend_to_note(&self, path: String, content: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `prepend_to_note`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PrependToNoteCallbackId`] can be passed to [`Self::remove_on_prepend_to_note`]
    /// to cancel the callback.
    fn on_prepend_to_note(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> PrependToNoteCallbackId;
    /// Cancel a callback previously registered by [`Self::on_prepend_to_note`],
    /// causing it not to run in the future.
    fn remove_on_prepend_to_note(&self, callback: PrependToNoteCallbackId);
}

impl prepend_to_note for super::RemoteReducers {
    fn prepend_to_note(&self, path: String, content: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("prepend_to_note", PrependToNoteArgs { path, content })
    }
    fn on_prepend_to_note(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> PrependToNoteCallbackId {
        PrependToNoteCallbackId(self.imp.on_reducer(
            "prepend_to_note",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PrependToNote { path, content },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, path, content)
            }),
        ))
    }
    fn remove_on_prepend_to_note(&self, callback: PrependToNoteCallbackId) {
        self.imp.remove_on_reducer("prepend_to_note", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `prepend_to_note`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_prepend_to_note {
    /// Set the call-reducer flags for the reducer `prepend_to_note` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn prepend_to_note(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_prepend_to_note for super::SetReducerFlags {
    fn prepend_to_note(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("prepend_to_note", flags);
    }
}
