// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushToolEventArgs {
    pub id: String,
    pub agent_id: String,
    pub tool: String,
    pub detail: String,
}

impl From<PushToolEventArgs> for super::Reducer {
    fn from(args: PushToolEventArgs) -> Self {
        Self::PushToolEvent {
            id: args.id,
            agent_id: args.agent_id,
            tool: args.tool,
            detail: args.detail,
        }
    }
}

impl __sdk::InModule for PushToolEventArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_tool_event`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_tool_event {
    /// Request that the remote module invoke the reducer `push_tool_event` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_tool_event:push_tool_event_then`] to run a callback after the reducer completes.
    fn push_tool_event(
        &self,
        id: String,
        agent_id: String,
        tool: String,
        detail: String,
    ) -> __sdk::Result<()> {
        self.push_tool_event_then(id, agent_id, tool, detail, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `push_tool_event` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_tool_event_then(
        &self,
        id: String,
        agent_id: String,
        tool: String,
        detail: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_tool_event for super::RemoteReducers {
    fn push_tool_event_then(
        &self,
        id: String,
        agent_id: String,
        tool: String,
        detail: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushToolEventArgs {
                id,
                agent_id,
                tool,
                detail,
            },
            callback,
        )
    }
}
