// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushImageArgs {
    pub id: String,
    pub session_id: String,
    pub caption: String,
    pub bytes: Vec<u8>,
}

impl From<PushImageArgs> for super::Reducer {
    fn from(args: PushImageArgs) -> Self {
        Self::PushImage {
            id: args.id,
            session_id: args.session_id,
            caption: args.caption,
            bytes: args.bytes,
        }
    }
}

impl __sdk::InModule for PushImageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_image`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_image {
    /// Request that the remote module invoke the reducer `push_image` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_image:push_image_then`] to run a callback after the reducer completes.
    fn push_image(
        &self,
        id: String,
        session_id: String,
        caption: String,
        bytes: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.push_image_then(id, session_id, caption, bytes, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `push_image` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_image_then(
        &self,
        id: String,
        session_id: String,
        caption: String,
        bytes: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_image for super::RemoteReducers {
    fn push_image_then(
        &self,
        id: String,
        session_id: String,
        caption: String,
        bytes: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushImageArgs {
                id,
                session_id,
                caption,
                bytes,
            },
            callback,
        )
    }
}
