// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::question_request_type::QuestionRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `question_request`.
///
/// Obtain a handle from the [`QuestionRequestTableAccess::question_request`] method on [`super::RemoteTables`],
/// like `ctx.db.question_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.question_request().on_insert(...)`.
pub struct QuestionRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<QuestionRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `question_request`.
///
/// Implemented for [`super::RemoteTables`].
pub trait QuestionRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`QuestionRequestTableHandle`], which mediates access to the table `question_request`.
    fn question_request(&self) -> QuestionRequestTableHandle<'_>;
}

impl QuestionRequestTableAccess for super::RemoteTables {
    fn question_request(&self) -> QuestionRequestTableHandle<'_> {
        QuestionRequestTableHandle {
            imp: self.imp.get_table::<QuestionRequest>("question_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct QuestionRequestInsertCallbackId(__sdk::CallbackId);
pub struct QuestionRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for QuestionRequestTableHandle<'ctx> {
    type Row = QuestionRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = QuestionRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = QuestionRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestionRequestInsertCallbackId {
        QuestionRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: QuestionRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = QuestionRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> QuestionRequestDeleteCallbackId {
        QuestionRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: QuestionRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct QuestionRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for QuestionRequestTableHandle<'ctx> {
    type UpdateCallbackId = QuestionRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> QuestionRequestUpdateCallbackId {
        QuestionRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: QuestionRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `question_request`,
/// which allows point queries on the field of the same name
/// via the [`QuestionRequestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.question_request().id().find(...)`.
pub struct QuestionRequestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<QuestionRequest, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> QuestionRequestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `question_request`.
    pub fn id(&self) -> QuestionRequestIdUnique<'ctx> {
        QuestionRequestIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> QuestionRequestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<QuestionRequest> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<QuestionRequest>("question_request");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<QuestionRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<QuestionRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `QuestionRequest`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait question_requestQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `QuestionRequest`.
    fn question_request(&self) -> __sdk::__query_builder::Table<QuestionRequest>;
}

impl question_requestQueryTableAccess for __sdk::QueryTableAccessor {
    fn question_request(&self) -> __sdk::__query_builder::Table<QuestionRequest> {
        __sdk::__query_builder::Table::new("question_request")
    }
}
