// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RenameFileArgs {
    pub id: String,
    pub new_path: String,
}

impl From<RenameFileArgs> for super::Reducer {
    fn from(args: RenameFileArgs) -> Self {
        Self::RenameFile {
            id: args.id,
            new_path: args.new_path,
        }
    }
}

impl __sdk::InModule for RenameFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `rename_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait rename_file {
    /// Request that the remote module invoke the reducer `rename_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`rename_file:rename_file_then`] to run a callback after the reducer completes.
    fn rename_file(&self, id: String, new_path: String) -> __sdk::Result<()> {
        self.rename_file_then(id, new_path, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `rename_file` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn rename_file_then(
        &self,
        id: String,
        new_path: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl rename_file for super::RemoteReducers {
    fn rename_file_then(
        &self,
        id: String,
        new_path: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RenameFileArgs { id, new_path }, callback)
    }
}
