// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestCallArgs {
    pub callee: __sdk::Identity,
}

impl From<RequestCallArgs> for super::Reducer {
    fn from(args: RequestCallArgs) -> Self {
        Self::RequestCall {
            callee: args.callee,
        }
    }
}

impl __sdk::InModule for RequestCallArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_call`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_call {
    /// Request that the remote module invoke the reducer `request_call` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_call:request_call_then`] to run a callback after the reducer completes.
    fn request_call(&self, callee: __sdk::Identity) -> __sdk::Result<()> {
        self.request_call_then(callee, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_call` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_call_then(
        &self,
        callee: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_call for super::RemoteReducers {
    fn request_call_then(
        &self,
        callee: __sdk::Identity,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RequestCallArgs { callee }, callback)
    }
}
