// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ResolvePermissionArgs {
    pub id: String,
    pub status: String,
}

impl From<ResolvePermissionArgs> for super::Reducer {
    fn from(args: ResolvePermissionArgs) -> Self {
        Self::ResolvePermission {
            id: args.id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for ResolvePermissionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `resolve_permission`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait resolve_permission {
    /// Request that the remote module invoke the reducer `resolve_permission` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`resolve_permission:resolve_permission_then`] to run a callback after the reducer completes.
    fn resolve_permission(&self, id: String, status: String) -> __sdk::Result<()> {
        self.resolve_permission_then(id, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `resolve_permission` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn resolve_permission_then(
        &self,
        id: String,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl resolve_permission for super::RemoteReducers {
    fn resolve_permission_then(
        &self,
        id: String,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ResolvePermissionArgs { id, status }, callback)
    }
}
