// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RespondToQuestionArgs {
    pub id: String,
    pub response: String,
}

impl From<RespondToQuestionArgs> for super::Reducer {
    fn from(args: RespondToQuestionArgs) -> Self {
        Self::RespondToQuestion {
            id: args.id,
            response: args.response,
        }
    }
}

impl __sdk::InModule for RespondToQuestionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `respond_to_question`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait respond_to_question {
    /// Request that the remote module invoke the reducer `respond_to_question` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`respond_to_question:respond_to_question_then`] to run a callback after the reducer completes.
    fn respond_to_question(&self, id: String, response: String) -> __sdk::Result<()> {
        self.respond_to_question_then(id, response, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `respond_to_question` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn respond_to_question_then(
        &self,
        id: String,
        response: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl respond_to_question for super::RemoteReducers {
    fn respond_to_question_then(
        &self,
        id: String,
        response: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RespondToQuestionArgs { id, response }, callback)
    }
}
