// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Session {
    pub id: String,
    pub base_name: String,
    pub host: String,
    pub client_id: String,
    pub created_at: __sdk::Timestamp,
    pub last_seen: __sdk::Timestamp,
    pub context_used: u64,
    pub context_window: u64,
}

impl __sdk::InModule for Session {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Session`.
///
/// Provides typed access to columns for query building.
pub struct SessionCols {
    pub id: __sdk::__query_builder::Col<Session, String>,
    pub base_name: __sdk::__query_builder::Col<Session, String>,
    pub host: __sdk::__query_builder::Col<Session, String>,
    pub client_id: __sdk::__query_builder::Col<Session, String>,
    pub created_at: __sdk::__query_builder::Col<Session, __sdk::Timestamp>,
    pub last_seen: __sdk::__query_builder::Col<Session, __sdk::Timestamp>,
    pub context_used: __sdk::__query_builder::Col<Session, u64>,
    pub context_window: __sdk::__query_builder::Col<Session, u64>,
}

impl __sdk::__query_builder::HasCols for Session {
    type Cols = SessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            base_name: __sdk::__query_builder::Col::new(table_name, "base_name"),
            host: __sdk::__query_builder::Col::new(table_name, "host"),
            client_id: __sdk::__query_builder::Col::new(table_name, "client_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            last_seen: __sdk::__query_builder::Col::new(table_name, "last_seen"),
            context_used: __sdk::__query_builder::Col::new(table_name, "context_used"),
            context_window: __sdk::__query_builder::Col::new(table_name, "context_window"),
        }
    }
}

/// Indexed column accessor struct for the table `Session`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionIxCols {
    pub id: __sdk::__query_builder::IxCol<Session, String>,
}

impl __sdk::__query_builder::HasIxCols for Session {
    type IxCols = SessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Session {}
