// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetA2ALimitsArgs {
    pub cooldown_secs: u32,
    pub hourly_limit: u32,
    pub max_hops: u32,
}

impl From<SetA2ALimitsArgs> for super::Reducer {
    fn from(args: SetA2ALimitsArgs) -> Self {
        Self::SetA2ALimits {
            cooldown_secs: args.cooldown_secs,
            hourly_limit: args.hourly_limit,
            max_hops: args.max_hops,
        }
    }
}

impl __sdk::InModule for SetA2ALimitsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_a2a_limits`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_a_2_a_limits {
    /// Request that the remote module invoke the reducer `set_a2a_limits` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_a_2_a_limits:set_a_2_a_limits_then`] to run a callback after the reducer completes.
    fn set_a_2_a_limits(
        &self,
        cooldown_secs: u32,
        hourly_limit: u32,
        max_hops: u32,
    ) -> __sdk::Result<()> {
        self.set_a_2_a_limits_then(cooldown_secs, hourly_limit, max_hops, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_a2a_limits` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_a_2_a_limits_then(
        &self,
        cooldown_secs: u32,
        hourly_limit: u32,
        max_hops: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_a_2_a_limits for super::RemoteReducers {
    fn set_a_2_a_limits_then(
        &self,
        cooldown_secs: u32,
        hourly_limit: u32,
        max_hops: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetA2ALimitsArgs {
                cooldown_secs,
                hourly_limit,
                max_hops,
            },
            callback,
        )
    }
}
