// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tool_event_type::ToolEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `tool_event`.
///
/// Obtain a handle from the [`ToolEventTableAccess::tool_event`] method on [`super::RemoteTables`],
/// like `ctx.db.tool_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tool_event().on_insert(...)`.
pub struct ToolEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ToolEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `tool_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ToolEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ToolEventTableHandle`], which mediates access to the table `tool_event`.
    fn tool_event(&self) -> ToolEventTableHandle<'_>;
}

impl ToolEventTableAccess for super::RemoteTables {
    fn tool_event(&self) -> ToolEventTableHandle<'_> {
        ToolEventTableHandle {
            imp: self.imp.get_table::<ToolEvent>("tool_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ToolEventInsertCallbackId(__sdk::CallbackId);
pub struct ToolEventDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ToolEventTableHandle<'ctx> {
    type Row = ToolEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ToolEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ToolEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ToolEventInsertCallbackId {
        ToolEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ToolEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ToolEventDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ToolEventDeleteCallbackId {
        ToolEventDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ToolEventDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ToolEventUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ToolEventTableHandle<'ctx> {
    type UpdateCallbackId = ToolEventUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ToolEventUpdateCallbackId {
        ToolEventUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ToolEventUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `tool_event`,
/// which allows point queries on the field of the same name
/// via the [`ToolEventIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.tool_event().id().find(...)`.
pub struct ToolEventIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ToolEvent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ToolEventTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `tool_event`.
    pub fn id(&self) -> ToolEventIdUnique<'ctx> {
        ToolEventIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ToolEventIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<ToolEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ToolEvent>("tool_event");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ToolEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ToolEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ToolEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait tool_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ToolEvent`.
    fn tool_event(&self) -> __sdk::__query_builder::Table<ToolEvent>;
}

impl tool_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn tool_event(&self) -> __sdk::__query_builder::Table<ToolEvent> {
        __sdk::__query_builder::Table::new("tool_event")
    }
}
