// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateNoteContentArgs {
    pub id: String,
    pub content: String,
    pub frontmatter: String,
    pub size: u64,
    pub modified_time: u64,
}

impl From<UpdateNoteContentArgs> for super::Reducer {
    fn from(args: UpdateNoteContentArgs) -> Self {
        Self::UpdateNoteContent {
            id: args.id,
            content: args.content,
            frontmatter: args.frontmatter,
            size: args.size,
            modified_time: args.modified_time,
        }
    }
}

impl __sdk::InModule for UpdateNoteContentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_note_content`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_note_content {
    /// Request that the remote module invoke the reducer `update_note_content` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_note_content:update_note_content_then`] to run a callback after the reducer completes.
    fn update_note_content(
        &self,
        id: String,
        content: String,
        frontmatter: String,
        size: u64,
        modified_time: u64,
    ) -> __sdk::Result<()> {
        self.update_note_content_then(id, content, frontmatter, size, modified_time, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_note_content` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_note_content_then(
        &self,
        id: String,
        content: String,
        frontmatter: String,
        size: u64,
        modified_time: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_note_content for super::RemoteReducers {
    fn update_note_content_then(
        &self,
        id: String,
        content: String,
        frontmatter: String,
        size: u64,
        modified_time: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateNoteContentArgs {
                id,
                content,
                frontmatter,
                size,
                modified_time,
            },
            callback,
        )
    }
}
