// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserProfile {
    pub identity: __sdk::Identity,
    pub name: String,
}

impl __sdk::InModule for UserProfile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserProfile`.
///
/// Provides typed access to columns for query building.
pub struct UserProfileCols {
    pub identity: __sdk::__query_builder::Col<UserProfile, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<UserProfile, String>,
}

impl __sdk::__query_builder::HasCols for UserProfile {
    type Cols = UserProfileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserProfileCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `UserProfile`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserProfileIxCols {
    pub identity: __sdk::__query_builder::IxCol<UserProfile, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for UserProfile {
    type IxCols = UserProfileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserProfileIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserProfile {}
