// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::user_profile_type::UserProfile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_profile`.
///
/// Obtain a handle from the [`UserProfileTableAccess::user_profile`] method on [`super::RemoteTables`],
/// like `ctx.db.user_profile()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_profile().on_insert(...)`.
pub struct UserProfileTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserProfile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_profile`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserProfileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserProfileTableHandle`], which mediates access to the table `user_profile`.
    fn user_profile(&self) -> UserProfileTableHandle<'_>;
}

impl UserProfileTableAccess for super::RemoteTables {
    fn user_profile(&self) -> UserProfileTableHandle<'_> {
        UserProfileTableHandle {
            imp: self.imp.get_table::<UserProfile>("user_profile"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserProfileInsertCallbackId(__sdk::CallbackId);
pub struct UserProfileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserProfileTableHandle<'ctx> {
    type Row = UserProfile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserProfile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserProfileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserProfileInsertCallbackId {
        UserProfileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserProfileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserProfileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserProfileDeleteCallbackId {
        UserProfileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserProfileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct UserProfileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserProfileTableHandle<'ctx> {
    type UpdateCallbackId = UserProfileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserProfileUpdateCallbackId {
        UserProfileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserProfileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `user_profile`,
/// which allows point queries on the field of the same name
/// via the [`UserProfileIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_profile().identity().find(...)`.
pub struct UserProfileIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserProfile, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserProfileTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `user_profile`.
    pub fn identity(&self) -> UserProfileIdentityUnique<'ctx> {
        UserProfileIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserProfileIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<UserProfile> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserProfile>("user_profile");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<UserProfile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserProfile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `UserProfile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait user_profileQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `UserProfile`.
    fn user_profile(&self) -> __sdk::__query_builder::Table<UserProfile>;
}

impl user_profileQueryTableAccess for __sdk::QueryTableAccessor {
    fn user_profile(&self) -> __sdk::__query_builder::Table<UserProfile> {
        __sdk::__query_builder::Table::new("user_profile")
    }
}
