// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AcceptCallArgs {
    pub session_id: u64,
}

impl From<AcceptCallArgs> for super::Reducer {
    fn from(args: AcceptCallArgs) -> Self {
        Self::AcceptCall {
            session_id: args.session_id,
        }
    }
}

impl __sdk::InModule for AcceptCallArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `accept_call`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait accept_call {
    /// Request that the remote module invoke the reducer `accept_call` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`accept_call:accept_call_then`] to run a callback after the reducer completes.
    fn accept_call(&self, session_id: u64) -> __sdk::Result<()> {
        self.accept_call_then(session_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `accept_call` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn accept_call_then(
        &self,
        session_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl accept_call for super::RemoteReducers {
    fn accept_call_then(
        &self,
        session_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AcceptCallArgs { session_id }, callback)
    }
}
