// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::agent_type::Agent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `agent`.
///
/// Obtain a handle from the [`AgentTableAccess::agent`] method on [`super::RemoteTables`],
/// like `ctx.db.agent()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent().on_insert(...)`.
pub struct AgentTableHandle<'ctx> {
    imp: __sdk::TableHandle<Agent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `agent`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AgentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AgentTableHandle`], which mediates access to the table `agent`.
    fn agent(&self) -> AgentTableHandle<'_>;
}

impl AgentTableAccess for super::RemoteTables {
    fn agent(&self) -> AgentTableHandle<'_> {
        AgentTableHandle {
            imp: self.imp.get_table::<Agent>("agent"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AgentInsertCallbackId(__sdk::CallbackId);
pub struct AgentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AgentTableHandle<'ctx> {
    type Row = Agent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Agent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AgentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentInsertCallbackId {
        AgentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AgentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AgentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AgentDeleteCallbackId {
        AgentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AgentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AgentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AgentTableHandle<'ctx> {
    type UpdateCallbackId = AgentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AgentUpdateCallbackId {
        AgentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AgentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `agent`,
/// which allows point queries on the field of the same name
/// via the [`AgentIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.agent().id().find(...)`.
pub struct AgentIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Agent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AgentTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `agent`.
    pub fn id(&self) -> AgentIdUnique<'ctx> {
        AgentIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AgentIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Agent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Agent>("agent");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Agent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Agent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Agent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait agentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Agent`.
    fn agent(&self) -> __sdk::__query_builder::Table<Agent>;
}

impl agentQueryTableAccess for __sdk::QueryTableAccessor {
    fn agent(&self) -> __sdk::__query_builder::Table<Agent> {
        __sdk::__query_builder::Table::new("agent")
    }
}
