// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendToNoteArgs {
    pub path: String,
    pub content: String,
}

impl From<AppendToNoteArgs> for super::Reducer {
    fn from(args: AppendToNoteArgs) -> Self {
        Self::AppendToNote {
            path: args.path,
            content: args.content,
        }
    }
}

impl __sdk::InModule for AppendToNoteArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_to_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_to_note {
    /// Request that the remote module invoke the reducer `append_to_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_to_note:append_to_note_then`] to run a callback after the reducer completes.
    fn append_to_note(&self, path: String, content: String) -> __sdk::Result<()> {
        self.append_to_note_then(path, content, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_to_note` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_to_note_then(
        &self,
        path: String,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_to_note for super::RemoteReducers {
    fn append_to_note_then(
        &self,
        path: String,
        content: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AppendToNoteArgs { path, content }, callback)
    }
}
