// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ArmSweepScheduleArgs {}

impl From<ArmSweepScheduleArgs> for super::Reducer {
    fn from(args: ArmSweepScheduleArgs) -> Self {
        Self::ArmSweepSchedule
    }
}

impl __sdk::InModule for ArmSweepScheduleArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `arm_sweep_schedule`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait arm_sweep_schedule {
    /// Request that the remote module invoke the reducer `arm_sweep_schedule` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`arm_sweep_schedule:arm_sweep_schedule_then`] to run a callback after the reducer completes.
    fn arm_sweep_schedule(&self) -> __sdk::Result<()> {
        self.arm_sweep_schedule_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `arm_sweep_schedule` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn arm_sweep_schedule_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl arm_sweep_schedule for super::RemoteReducers {
    fn arm_sweep_schedule_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ArmSweepScheduleArgs {}, callback)
    }
}
