// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AudioFrame {
    pub session_id: u64,
    pub from: __sdk::Identity,
    pub seq: u32,
    pub pcm: Vec<u8>,
}

impl __sdk::InModule for AudioFrame {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AudioFrame`.
///
/// Provides typed access to columns for query building.
pub struct AudioFrameCols {
    pub session_id: __sdk::__query_builder::Col<AudioFrame, u64>,
    pub from: __sdk::__query_builder::Col<AudioFrame, __sdk::Identity>,
    pub seq: __sdk::__query_builder::Col<AudioFrame, u32>,
    pub pcm: __sdk::__query_builder::Col<AudioFrame, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for AudioFrame {
    type Cols = AudioFrameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AudioFrameCols {
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            from: __sdk::__query_builder::Col::new(table_name, "from"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            pcm: __sdk::__query_builder::Col::new(table_name, "pcm"),
        }
    }
}

/// Indexed column accessor struct for the table `AudioFrame`.
///
/// Provides typed access to indexed columns for query building.
pub struct AudioFrameIxCols {}

impl __sdk::__query_builder::HasIxCols for AudioFrame {
    type IxCols = AudioFrameIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AudioFrameIxCols {}
    }
}
