// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::audio_frame_type::AudioFrame;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `audio_frame`.
///
/// Obtain a handle from the [`AudioFrameTableAccess::audio_frame`] method on [`super::RemoteTables`],
/// like `ctx.db.audio_frame()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.audio_frame().on_insert(...)`.
pub struct AudioFrameTableHandle<'ctx> {
    imp: __sdk::TableHandle<AudioFrame>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `audio_frame`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AudioFrameTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AudioFrameTableHandle`], which mediates access to the table `audio_frame`.
    fn audio_frame(&self) -> AudioFrameTableHandle<'_>;
}

impl AudioFrameTableAccess for super::RemoteTables {
    fn audio_frame(&self) -> AudioFrameTableHandle<'_> {
        AudioFrameTableHandle {
            imp: self.imp.get_table::<AudioFrame>("audio_frame"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AudioFrameInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::EventTable for AudioFrameTableHandle<'ctx> {
    type Row = AudioFrame;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AudioFrame> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AudioFrameInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AudioFrameInsertCallbackId {
        AudioFrameInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AudioFrameInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AudioFrame>("audio_frame");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AudioFrame>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AudioFrame>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AudioFrame`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait audio_frameQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AudioFrame`.
    fn audio_frame(&self) -> __sdk::__query_builder::Table<AudioFrame>;
}

impl audio_frameQueryTableAccess for __sdk::QueryTableAccessor {
    fn audio_frame(&self) -> __sdk::__query_builder::Table<AudioFrame> {
        __sdk::__query_builder::Table::new("audio_frame")
    }
}
