// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::call_state_type::CallState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CallSession {
    pub agent_id: u64,
    pub caller: __sdk::Identity,
    pub callee: __sdk::Identity,
    pub state: CallState,
}

impl __sdk::InModule for CallSession {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CallSession`.
///
/// Provides typed access to columns for query building.
pub struct CallSessionCols {
    pub agent_id: __sdk::__query_builder::Col<CallSession, u64>,
    pub caller: __sdk::__query_builder::Col<CallSession, __sdk::Identity>,
    pub callee: __sdk::__query_builder::Col<CallSession, __sdk::Identity>,
    pub state: __sdk::__query_builder::Col<CallSession, CallState>,
}

impl __sdk::__query_builder::HasCols for CallSession {
    type Cols = CallSessionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CallSessionCols {
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            caller: __sdk::__query_builder::Col::new(table_name, "caller"),
            callee: __sdk::__query_builder::Col::new(table_name, "callee"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
        }
    }
}

/// Indexed column accessor struct for the table `CallSession`.
///
/// Provides typed access to indexed columns for query building.
pub struct CallSessionIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<CallSession, u64>,
}

impl __sdk::__query_builder::HasIxCols for CallSession {
    type IxCols = CallSessionIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CallSessionIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CallSession {}
