// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearAllArgs {}

impl From<ClearAllArgs> for super::Reducer {
    fn from(args: ClearAllArgs) -> Self {
        Self::ClearAll
    }
}

impl __sdk::InModule for ClearAllArgs {
    type Module = super::RemoteModule;
}

pub struct ClearAllCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_all`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_all {
    /// Request that the remote module invoke the reducer `clear_all` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_clear_all`] callbacks.
    fn clear_all(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `clear_all`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClearAllCallbackId`] can be passed to [`Self::remove_on_clear_all`]
    /// to cancel the callback.
    fn on_clear_all(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClearAllCallbackId;
    /// Cancel a callback previously registered by [`Self::on_clear_all`],
    /// causing it not to run in the future.
    fn remove_on_clear_all(&self, callback: ClearAllCallbackId);
}

impl clear_all for super::RemoteReducers {
    fn clear_all(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("clear_all", ClearAllArgs {})
    }
    fn on_clear_all(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ClearAllCallbackId {
        ClearAllCallbackId(self.imp.on_reducer(
            "clear_all",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClearAll {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_clear_all(&self, callback: ClearAllCallbackId) {
        self.imp.remove_on_reducer("clear_all", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `clear_all`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_clear_all {
    /// Set the call-reducer flags for the reducer `clear_all` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn clear_all(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_clear_all for super::SetReducerFlags {
    fn clear_all(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("clear_all", flags);
    }
}
