// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::connected_user_type::ConnectedUser;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `connected_user`.
///
/// Obtain a handle from the [`ConnectedUserTableAccess::connected_user`] method on [`super::RemoteTables`],
/// like `ctx.db.connected_user()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connected_user().on_insert(...)`.
pub struct ConnectedUserTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConnectedUser>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `connected_user`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConnectedUserTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConnectedUserTableHandle`], which mediates access to the table `connected_user`.
    fn connected_user(&self) -> ConnectedUserTableHandle<'_>;
}

impl ConnectedUserTableAccess for super::RemoteTables {
    fn connected_user(&self) -> ConnectedUserTableHandle<'_> {
        ConnectedUserTableHandle {
            imp: self.imp.get_table::<ConnectedUser>("connected_user"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConnectedUserInsertCallbackId(__sdk::CallbackId);
pub struct ConnectedUserDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConnectedUserTableHandle<'ctx> {
    type Row = ConnectedUser;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConnectedUser> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConnectedUserInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectedUserInsertCallbackId {
        ConnectedUserInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConnectedUserInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConnectedUserDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConnectedUserDeleteCallbackId {
        ConnectedUserDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConnectedUserDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct ConnectedUserUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConnectedUserTableHandle<'ctx> {
    type UpdateCallbackId = ConnectedUserUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConnectedUserUpdateCallbackId {
        ConnectedUserUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConnectedUserUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `connected_user`,
/// which allows point queries on the field of the same name
/// via the [`ConnectedUserIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.connected_user().identity().find(...)`.
pub struct ConnectedUserIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ConnectedUser, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConnectedUserTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `connected_user`.
    pub fn identity(&self) -> ConnectedUserIdentityUnique<'ctx> {
        ConnectedUserIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConnectedUserIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<ConnectedUser> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ConnectedUser>("connected_user");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ConnectedUser>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConnectedUser>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ConnectedUser`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait connected_userQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ConnectedUser`.
    fn connected_user(&self) -> __sdk::__query_builder::Table<ConnectedUser>;
}

impl connected_userQueryTableAccess for __sdk::QueryTableAccessor {
    fn connected_user(&self) -> __sdk::__query_builder::Table<ConnectedUser> {
        __sdk::__query_builder::Table::new("connected_user")
    }
}
