// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ConnectedUser {
    pub identity: __sdk::Identity,
    pub connected_at: u64,
    pub name: String,
}

impl __sdk::InModule for ConnectedUser {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ConnectedUser`.
///
/// Provides typed access to columns for query building.
pub struct ConnectedUserCols {
    pub identity: __sdk::__query_builder::Col<ConnectedUser, __sdk::Identity>,
    pub connected_at: __sdk::__query_builder::Col<ConnectedUser, u64>,
    pub name: __sdk::__query_builder::Col<ConnectedUser, String>,
}

impl __sdk::__query_builder::HasCols for ConnectedUser {
    type Cols = ConnectedUserCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ConnectedUserCols {
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            connected_at: __sdk::__query_builder::Col::new(table_name, "connected_at"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
        }
    }
}

/// Indexed column accessor struct for the table `ConnectedUser`.
///
/// Provides typed access to indexed columns for query building.
pub struct ConnectedUserIxCols {
    pub identity: __sdk::__query_builder::IxCol<ConnectedUser, __sdk::Identity>,
}

impl __sdk::__query_builder::HasIxCols for ConnectedUser {
    type IxCols = ConnectedUserIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ConnectedUserIxCols {
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ConnectedUser {}
