// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateFolderArgs {
    pub path: String,
    pub name: String,
    pub depth: u32,
}

impl From<CreateFolderArgs> for super::Reducer {
    fn from(args: CreateFolderArgs) -> Self {
        Self::CreateFolder {
            path: args.path,
            name: args.name,
            depth: args.depth,
        }
    }
}

impl __sdk::InModule for CreateFolderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_folder`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_folder {
    /// Request that the remote module invoke the reducer `create_folder` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_folder:create_folder_then`] to run a callback after the reducer completes.
    fn create_folder(&self, path: String, name: String, depth: u32) -> __sdk::Result<()> {
        self.create_folder_then(path, name, depth, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_folder` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_folder_then(
        &self,
        path: String,
        name: String,
        depth: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_folder for super::RemoteReducers {
    fn create_folder_then(
        &self,
        path: String,
        name: String,
        depth: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateFolderArgs { path, name, depth }, callback)
    }
}
