// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateFileArgs {
    pub id: String,
    pub path: String,
    pub name: String,
    pub content: String,
    pub folder_path: String,
    pub depth: u32,
    pub extension: String,
    pub size: u64,
    pub created_time: u64,
    pub modified_time: u64,
}

impl From<CreateFileArgs> for super::Reducer {
    fn from(args: CreateFileArgs) -> Self {
        Self::CreateFile {
            id: args.id,
            path: args.path,
            name: args.name,
            content: args.content,
            folder_path: args.folder_path,
            depth: args.depth,
            extension: args.extension,
            size: args.size,
            created_time: args.created_time,
            modified_time: args.modified_time,
        }
    }
}

impl __sdk::InModule for CreateFileArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_file`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_file {
    /// Request that the remote module invoke the reducer `create_file` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_file:create_file_then`] to run a callback after the reducer completes.
    fn create_file(
        &self,
        id: String,
        path: String,
        name: String,
        content: String,
        folder_path: String,
        depth: u32,
        extension: String,
        size: u64,
        created_time: u64,
        modified_time: u64,
    ) -> __sdk::Result<()> {
        self.create_file_then(
            id,
            path,
            name,
            content,
            folder_path,
            depth,
            extension,
            size,
            created_time,
            modified_time,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `create_file` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_file_then(
        &self,
        id: String,
        path: String,
        name: String,
        content: String,
        folder_path: String,
        depth: u32,
        extension: String,
        size: u64,
        created_time: u64,
        modified_time: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_file for super::RemoteReducers {
    fn create_file_then(
        &self,
        id: String,
        path: String,
        name: String,
        content: String,
        folder_path: String,
        depth: u32,
        extension: String,
        size: u64,
        created_time: u64,
        modified_time: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateFileArgs {
                id,
                path,
                name,
                content,
                folder_path,
                depth,
                extension,
                size,
                created_time,
                modified_time,
            },
            callback,
        )
    }
}
