// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteNoteArgs {
    pub id: String,
}

impl From<DeleteNoteArgs> for super::Reducer {
    fn from(args: DeleteNoteArgs) -> Self {
        Self::DeleteNote { id: args.id }
    }
}

impl __sdk::InModule for DeleteNoteArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteNoteCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_note`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_note {
    /// Request that the remote module invoke the reducer `delete_note` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_note`] callbacks.
    fn delete_note(&self, id: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_note`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteNoteCallbackId`] can be passed to [`Self::remove_on_delete_note`]
    /// to cancel the callback.
    fn on_delete_note(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> DeleteNoteCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_note`],
    /// causing it not to run in the future.
    fn remove_on_delete_note(&self, callback: DeleteNoteCallbackId);
}

impl delete_note for super::RemoteReducers {
    fn delete_note(&self, id: String) -> __sdk::Result<()> {
        self.imp.call_reducer("delete_note", DeleteNoteArgs { id })
    }
    fn on_delete_note(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> DeleteNoteCallbackId {
        DeleteNoteCallbackId(self.imp.on_reducer(
            "delete_note",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteNote { id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id)
            }),
        ))
    }
    fn remove_on_delete_note(&self, callback: DeleteNoteCallbackId) {
        self.imp.remove_on_reducer("delete_note", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_note`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_note {
    /// Set the call-reducer flags for the reducer `delete_note` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_note(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_note for super::SetReducerFlags {
    fn delete_note(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_note", flags);
    }
}
