// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::file_content_type::FileContent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `file_content`.
///
/// Obtain a handle from the [`FileContentTableAccess::file_content`] method on [`super::RemoteTables`],
/// like `ctx.db.file_content()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.file_content().on_insert(...)`.
pub struct FileContentTableHandle<'ctx> {
    imp: __sdk::TableHandle<FileContent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `file_content`.
pub struct FileContentTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for FileContentTableAccessor {
    type Row = FileContent;
    type Handle<'db> = FileContentTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.file_content()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `file_content`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FileContentTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FileContentTableHandle`], which mediates access to the table `file_content`.
    fn file_content(&self) -> FileContentTableHandle<'_>;
}

impl FileContentTableAccess for super::RemoteTables {
    fn file_content(&self) -> FileContentTableHandle<'_> {
        FileContentTableHandle {
            imp: self.imp.get_table::<FileContent>("file_content"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FileContentInsertCallbackId(__sdk::CallbackId);
pub struct FileContentDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for FileContentTableHandle<'ctx> {
    type Row = FileContent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FileContent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for FileContentTableHandle<'ctx> {
    type Row = FileContent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FileContent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FileContentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FileContentInsertCallbackId {
        FileContentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FileContentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FileContentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FileContentDeleteCallbackId {
        FileContentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FileContentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for FileContentTableHandle<'ctx> {
    type InsertCallbackId = FileContentInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FileContentInsertCallbackId {
        FileContentInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FileContentInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for FileContentTableHandle<'ctx> {
    type DeleteCallbackId = FileContentDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FileContentDeleteCallbackId {
        FileContentDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FileContentDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct FileContentUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FileContentTableHandle<'ctx> {
    type UpdateCallbackId = FileContentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FileContentUpdateCallbackId {
        FileContentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FileContentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for FileContentTableHandle<'ctx> {
    type UpdateCallbackId = FileContentUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FileContentUpdateCallbackId {
        FileContentUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FileContentUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `file_id` unique index on the table `file_content`,
/// which allows point queries on the field of the same name
/// via the [`FileContentFileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.file_content().file_id().find(...)`.
pub struct FileContentFileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FileContent, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FileContentTableHandle<'ctx> {
    /// Get a handle on the `file_id` unique index on the table `file_content`.
    pub fn file_id(&self) -> FileContentFileIdUnique<'ctx> {
        FileContentFileIdUnique {
            imp: self.imp.get_unique_constraint::<String>("file_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FileContentFileIdUnique<'ctx> {
    /// Find the subscribed row whose `file_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<FileContent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FileContent>("file_content");
    _table.add_unique_constraint::<String>("file_id", |row| &row.file_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FileContent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FileContent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FileContent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait file_contentQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FileContent`.
    fn file_content(&self) -> __sdk::__query_builder::Table<FileContent>;
}

impl file_contentQueryTableAccess for __sdk::QueryTableAccessor {
    fn file_content(&self) -> __sdk::__query_builder::Table<FileContent> {
        __sdk::__query_builder::Table::new("file_content")
    }
}
