// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FileContent {
    pub file_id: String,
    pub content: String,
}

impl __sdk::InModule for FileContent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FileContent`.
///
/// Provides typed access to columns for query building.
pub struct FileContentCols {
    pub file_id: __sdk::__query_builder::Col<FileContent, String>,
    pub content: __sdk::__query_builder::Col<FileContent, String>,
}

impl __sdk::__query_builder::HasCols for FileContent {
    type Cols = FileContentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FileContentCols {
            file_id: __sdk::__query_builder::Col::new(table_name, "file_id"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
        }
    }
}

/// Indexed column accessor struct for the table `FileContent`.
///
/// Provides typed access to indexed columns for query building.
pub struct FileContentIxCols {
    pub file_id: __sdk::__query_builder::IxCol<FileContent, String>,
}

impl __sdk::__query_builder::HasIxCols for FileContent {
    type IxCols = FileContentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FileContentIxCols {
            file_id: __sdk::__query_builder::IxCol::new(table_name, "file_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FileContent {}
