// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::folder_type::Folder;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `folder`.
///
/// Obtain a handle from the [`FolderTableAccess::folder`] method on [`super::RemoteTables`],
/// like `ctx.db.folder()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.folder().on_insert(...)`.
pub struct FolderTableHandle<'ctx> {
    imp: __sdk::TableHandle<Folder>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `folder`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FolderTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FolderTableHandle`], which mediates access to the table `folder`.
    fn folder(&self) -> FolderTableHandle<'_>;
}

impl FolderTableAccess for super::RemoteTables {
    fn folder(&self) -> FolderTableHandle<'_> {
        FolderTableHandle {
            imp: self.imp.get_table::<Folder>("folder"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FolderInsertCallbackId(__sdk::CallbackId);
pub struct FolderDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FolderTableHandle<'ctx> {
    type Row = Folder;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Folder> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FolderInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FolderInsertCallbackId {
        FolderInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FolderInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FolderDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FolderDeleteCallbackId {
        FolderDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FolderDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Folder>("folder");
    _table.add_unique_constraint::<String>("path", |row| &row.path);
}
pub struct FolderUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FolderTableHandle<'ctx> {
    type UpdateCallbackId = FolderUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FolderUpdateCallbackId {
        FolderUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FolderUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Folder>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Folder>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `path` unique index on the table `folder`,
/// which allows point queries on the field of the same name
/// via the [`FolderPathUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.folder().path().find(...)`.
pub struct FolderPathUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Folder, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FolderTableHandle<'ctx> {
    /// Get a handle on the `path` unique index on the table `folder`.
    pub fn path(&self) -> FolderPathUnique<'ctx> {
        FolderPathUnique {
            imp: self.imp.get_unique_constraint::<String>("path"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FolderPathUnique<'ctx> {
    /// Find the subscribed row whose `path` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<Folder> {
        self.imp.find(col_val)
    }
}
