// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct GetRecentNotesArgs {
    pub limit: u32,
}

impl From<GetRecentNotesArgs> for super::Reducer {
    fn from(args: GetRecentNotesArgs) -> Self {
        Self::GetRecentNotes { limit: args.limit }
    }
}

impl __sdk::InModule for GetRecentNotesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `get_recent_notes`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait get_recent_notes {
    /// Request that the remote module invoke the reducer `get_recent_notes` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`get_recent_notes:get_recent_notes_then`] to run a callback after the reducer completes.
    fn get_recent_notes(&self, limit: u32) -> __sdk::Result<()> {
        self.get_recent_notes_then(limit, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `get_recent_notes` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn get_recent_notes_then(
        &self,
        limit: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl get_recent_notes for super::RemoteReducers {
    fn get_recent_notes_then(
        &self,
        limit: u32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(GetRecentNotesArgs { limit }, callback)
    }
}
