// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_image_type::MessageImage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `message_image`.
///
/// Obtain a handle from the [`MessageImageTableAccess::message_image`] method on [`super::RemoteTables`],
/// like `ctx.db.message_image()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.message_image().on_insert(...)`.
pub struct MessageImageTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessageImage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `message_image`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MessageImageTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MessageImageTableHandle`], which mediates access to the table `message_image`.
    fn message_image(&self) -> MessageImageTableHandle<'_>;
}

impl MessageImageTableAccess for super::RemoteTables {
    fn message_image(&self) -> MessageImageTableHandle<'_> {
        MessageImageTableHandle {
            imp: self.imp.get_table::<MessageImage>("message_image"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MessageImageInsertCallbackId(__sdk::CallbackId);
pub struct MessageImageDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MessageImageTableHandle<'ctx> {
    type Row = MessageImage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageImage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MessageImageInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MessageImageInsertCallbackId {
        MessageImageInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MessageImageInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MessageImageDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MessageImageDeleteCallbackId {
        MessageImageDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MessageImageDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct MessageImageUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MessageImageTableHandle<'ctx> {
    type UpdateCallbackId = MessageImageUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MessageImageUpdateCallbackId {
        MessageImageUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MessageImageUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `message_id` unique index on the table `message_image`,
/// which allows point queries on the field of the same name
/// via the [`MessageImageMessageIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.message_image().message_id().find(...)`.
pub struct MessageImageMessageIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MessageImage, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MessageImageTableHandle<'ctx> {
    /// Get a handle on the `message_id` unique index on the table `message_image`.
    pub fn message_id(&self) -> MessageImageMessageIdUnique<'ctx> {
        MessageImageMessageIdUnique {
            imp: self.imp.get_unique_constraint::<String>("message_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MessageImageMessageIdUnique<'ctx> {
    /// Find the subscribed row whose `message_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MessageImage> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MessageImage>("message_image");
    _table.add_unique_constraint::<String>("message_id", |row| &row.message_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessageImage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessageImage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessageImage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait message_imageQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessageImage`.
    fn message_image(&self) -> __sdk::__query_builder::Table<MessageImage>;
}

impl message_imageQueryTableAccess for __sdk::QueryTableAccessor {
    fn message_image(&self) -> __sdk::__query_builder::Table<MessageImage> {
        __sdk::__query_builder::Table::new("message_image")
    }
}
