// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PermissionRequest {
    pub id: String,
    pub agent_id: String,
    pub tool: String,
    pub input: String,
    pub status: String,
    pub created_at: __sdk::Timestamp,
    pub resolved_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for PermissionRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PermissionRequest`.
///
/// Provides typed access to columns for query building.
pub struct PermissionRequestCols {
    pub id: __sdk::__query_builder::Col<PermissionRequest, String>,
    pub agent_id: __sdk::__query_builder::Col<PermissionRequest, String>,
    pub tool: __sdk::__query_builder::Col<PermissionRequest, String>,
    pub input: __sdk::__query_builder::Col<PermissionRequest, String>,
    pub status: __sdk::__query_builder::Col<PermissionRequest, String>,
    pub created_at: __sdk::__query_builder::Col<PermissionRequest, __sdk::Timestamp>,
    pub resolved_at: __sdk::__query_builder::Col<PermissionRequest, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for PermissionRequest {
    type Cols = PermissionRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PermissionRequestCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            tool: __sdk::__query_builder::Col::new(table_name, "tool"),
            input: __sdk::__query_builder::Col::new(table_name, "input"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            resolved_at: __sdk::__query_builder::Col::new(table_name, "resolved_at"),
        }
    }
}

/// Indexed column accessor struct for the table `PermissionRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct PermissionRequestIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<PermissionRequest, String>,
    pub id: __sdk::__query_builder::IxCol<PermissionRequest, String>,
}

impl __sdk::__query_builder::HasIxCols for PermissionRequest {
    type IxCols = PermissionRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PermissionRequestIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for PermissionRequest {}
