// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushContextUsageArgs {
    pub session_id: String,
    pub used: u64,
    pub window: u64,
}

impl From<PushContextUsageArgs> for super::Reducer {
    fn from(args: PushContextUsageArgs) -> Self {
        Self::PushContextUsage {
            session_id: args.session_id,
            used: args.used,
            window: args.window,
        }
    }
}

impl __sdk::InModule for PushContextUsageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_context_usage`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_context_usage {
    /// Request that the remote module invoke the reducer `push_context_usage` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_context_usage:push_context_usage_then`] to run a callback after the reducer completes.
    fn push_context_usage(&self, session_id: String, used: u64, window: u64) -> __sdk::Result<()> {
        self.push_context_usage_then(session_id, used, window, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `push_context_usage` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_context_usage_then(
        &self,
        session_id: String,
        used: u64,
        window: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_context_usage for super::RemoteReducers {
    fn push_context_usage_then(
        &self,
        session_id: String,
        used: u64,
        window: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushContextUsageArgs {
                session_id,
                used,
                window,
            },
            callback,
        )
    }
}
