// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushStatusArgs {
    pub agent_id: String,
    pub state: String,
}

impl From<PushStatusArgs> for super::Reducer {
    fn from(args: PushStatusArgs) -> Self {
        Self::PushStatus {
            agent_id: args.agent_id,
            state: args.state,
        }
    }
}

impl __sdk::InModule for PushStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_status {
    /// Request that the remote module invoke the reducer `push_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_status:push_status_then`] to run a callback after the reducer completes.
    fn push_status(&self, agent_id: String, state: String) -> __sdk::Result<()> {
        self.push_status_then(agent_id, state, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `push_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_status_then(
        &self,
        agent_id: String,
        state: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_status for super::RemoteReducers {
    fn push_status_then(
        &self,
        agent_id: String,
        state: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PushStatusArgs { agent_id, state }, callback)
    }
}
