// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PushMessageArgs {
    pub id: String,
    pub agent_id: String,
    pub role: String,
    pub text: String,
    pub source: String,
}

impl From<PushMessageArgs> for super::Reducer {
    fn from(args: PushMessageArgs) -> Self {
        Self::PushMessage {
            id: args.id,
            agent_id: args.agent_id,
            role: args.role,
            text: args.text,
            source: args.source,
        }
    }
}

impl __sdk::InModule for PushMessageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `push_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait push_message {
    /// Request that the remote module invoke the reducer `push_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`push_message:push_message_then`] to run a callback after the reducer completes.
    fn push_message(
        &self,
        id: String,
        agent_id: String,
        role: String,
        text: String,
        source: String,
    ) -> __sdk::Result<()> {
        self.push_message_then(id, agent_id, role, text, source, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `push_message` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn push_message_then(
        &self,
        id: String,
        agent_id: String,
        role: String,
        text: String,
        source: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl push_message for super::RemoteReducers {
    fn push_message_then(
        &self,
        id: String,
        agent_id: String,
        role: String,
        text: String,
        source: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            PushMessageArgs {
                id,
                agent_id,
                role,
                text,
                source,
            },
            callback,
        )
    }
}
