// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct QuestionRequest {
    pub id: String,
    pub agent_id: String,
    pub question: String,
    pub header: String,
    pub options: String,
    pub multi_select: bool,
    pub status: String,
    pub response: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub resolved_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for QuestionRequest {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `QuestionRequest`.
///
/// Provides typed access to columns for query building.
pub struct QuestionRequestCols {
    pub id: __sdk::__query_builder::Col<QuestionRequest, String>,
    pub agent_id: __sdk::__query_builder::Col<QuestionRequest, String>,
    pub question: __sdk::__query_builder::Col<QuestionRequest, String>,
    pub header: __sdk::__query_builder::Col<QuestionRequest, String>,
    pub options: __sdk::__query_builder::Col<QuestionRequest, String>,
    pub multi_select: __sdk::__query_builder::Col<QuestionRequest, bool>,
    pub status: __sdk::__query_builder::Col<QuestionRequest, String>,
    pub response: __sdk::__query_builder::Col<QuestionRequest, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<QuestionRequest, __sdk::Timestamp>,
    pub resolved_at: __sdk::__query_builder::Col<QuestionRequest, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for QuestionRequest {
    type Cols = QuestionRequestCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        QuestionRequestCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            agent_id: __sdk::__query_builder::Col::new(table_name, "agent_id"),
            question: __sdk::__query_builder::Col::new(table_name, "question"),
            header: __sdk::__query_builder::Col::new(table_name, "header"),
            options: __sdk::__query_builder::Col::new(table_name, "options"),
            multi_select: __sdk::__query_builder::Col::new(table_name, "multi_select"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            response: __sdk::__query_builder::Col::new(table_name, "response"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            resolved_at: __sdk::__query_builder::Col::new(table_name, "resolved_at"),
        }
    }
}

/// Indexed column accessor struct for the table `QuestionRequest`.
///
/// Provides typed access to indexed columns for query building.
pub struct QuestionRequestIxCols {
    pub agent_id: __sdk::__query_builder::IxCol<QuestionRequest, String>,
    pub id: __sdk::__query_builder::IxCol<QuestionRequest, String>,
}

impl __sdk::__query_builder::HasIxCols for QuestionRequest {
    type IxCols = QuestionRequestIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        QuestionRequestIxCols {
            agent_id: __sdk::__query_builder::IxCol::new(table_name, "agent_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for QuestionRequest {}
