// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestPermissionArgs {
    pub id: String,
    pub agent_id: String,
    pub tool: String,
    pub input: String,
}

impl From<RequestPermissionArgs> for super::Reducer {
    fn from(args: RequestPermissionArgs) -> Self {
        Self::RequestPermission {
            id: args.id,
            agent_id: args.agent_id,
            tool: args.tool,
            input: args.input,
        }
    }
}

impl __sdk::InModule for RequestPermissionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_permission`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_permission {
    /// Request that the remote module invoke the reducer `request_permission` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_permission:request_permission_then`] to run a callback after the reducer completes.
    fn request_permission(
        &self,
        id: String,
        agent_id: String,
        tool: String,
        input: String,
    ) -> __sdk::Result<()> {
        self.request_permission_then(id, agent_id, tool, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `request_permission` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_permission_then(
        &self,
        id: String,
        agent_id: String,
        tool: String,
        input: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_permission for super::RemoteReducers {
    fn request_permission_then(
        &self,
        id: String,
        agent_id: String,
        tool: String,
        input: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestPermissionArgs {
                id,
                agent_id,
                tool,
                input,
            },
            callback,
        )
    }
}
