// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestQuestionArgs {
    pub id: String,
    pub agent_id: String,
    pub question: String,
    pub header: String,
    pub options: String,
    pub multi_select: bool,
}

impl From<RequestQuestionArgs> for super::Reducer {
    fn from(args: RequestQuestionArgs) -> Self {
        Self::RequestQuestion {
            id: args.id,
            agent_id: args.agent_id,
            question: args.question,
            header: args.header,
            options: args.options,
            multi_select: args.multi_select,
        }
    }
}

impl __sdk::InModule for RequestQuestionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_question`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_question {
    /// Request that the remote module invoke the reducer `request_question` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_question:request_question_then`] to run a callback after the reducer completes.
    fn request_question(
        &self,
        id: String,
        agent_id: String,
        question: String,
        header: String,
        options: String,
        multi_select: bool,
    ) -> __sdk::Result<()> {
        self.request_question_then(
            id,
            agent_id,
            question,
            header,
            options,
            multi_select,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `request_question` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_question_then(
        &self,
        id: String,
        agent_id: String,
        question: String,
        header: String,
        options: String,
        multi_select: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_question for super::RemoteReducers {
    fn request_question_then(
        &self,
        id: String,
        agent_id: String,
        question: String,
        header: String,
        options: String,
        multi_select: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestQuestionArgs {
                id,
                agent_id,
                question,
                header,
                options,
                multi_select,
            },
            callback,
        )
    }
}
