// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendVideoFrameArgs {
    pub agent_id: u64,
    pub seq: u32,
    pub codec: u8,
    pub is_keyframe: bool,
    pub data: Vec<u8>,
}

impl From<SendVideoFrameArgs> for super::Reducer {
    fn from(args: SendVideoFrameArgs) -> Self {
        Self::SendVideoFrame {
            agent_id: args.agent_id,
            seq: args.seq,
            codec: args.codec,
            is_keyframe: args.is_keyframe,
            data: args.data,
        }
    }
}

impl __sdk::InModule for SendVideoFrameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_video_frame`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_video_frame {
    /// Request that the remote module invoke the reducer `send_video_frame` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`send_video_frame:send_video_frame_then`] to run a callback after the reducer completes.
    fn send_video_frame(
        &self,
        agent_id: u64,
        seq: u32,
        codec: u8,
        is_keyframe: bool,
        data: Vec<u8>,
    ) -> __sdk::Result<()> {
        self.send_video_frame_then(agent_id, seq, codec, is_keyframe, data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `send_video_frame` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn send_video_frame_then(
        &self,
        agent_id: u64,
        seq: u32,
        codec: u8,
        is_keyframe: bool,
        data: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl send_video_frame for super::RemoteReducers {
    fn send_video_frame_then(
        &self,
        agent_id: u64,
        seq: u32,
        codec: u8,
        is_keyframe: bool,
        data: Vec<u8>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SendVideoFrameArgs {
                agent_id,
                seq,
                codec,
                is_keyframe,
                data,
            },
            callback,
        )
    }
}
