// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::session_activity_type::SessionActivity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `session_activity`.
///
/// Obtain a handle from the [`SessionActivityTableAccess::session_activity`] method on [`super::RemoteTables`],
/// like `ctx.db.session_activity()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.session_activity().on_insert(...)`.
pub struct SessionActivityTableHandle<'ctx> {
    imp: __sdk::TableHandle<SessionActivity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `session_activity`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SessionActivityTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SessionActivityTableHandle`], which mediates access to the table `session_activity`.
    fn session_activity(&self) -> SessionActivityTableHandle<'_>;
}

impl SessionActivityTableAccess for super::RemoteTables {
    fn session_activity(&self) -> SessionActivityTableHandle<'_> {
        SessionActivityTableHandle {
            imp: self.imp.get_table::<SessionActivity>("session_activity"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SessionActivityInsertCallbackId(__sdk::CallbackId);
pub struct SessionActivityDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SessionActivityTableHandle<'ctx> {
    type Row = SessionActivity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SessionActivity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SessionActivityInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionActivityInsertCallbackId {
        SessionActivityInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SessionActivityInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SessionActivityDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SessionActivityDeleteCallbackId {
        SessionActivityDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SessionActivityDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SessionActivityUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SessionActivityTableHandle<'ctx> {
    type UpdateCallbackId = SessionActivityUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SessionActivityUpdateCallbackId {
        SessionActivityUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SessionActivityUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `session_id` unique index on the table `session_activity`,
/// which allows point queries on the field of the same name
/// via the [`SessionActivitySessionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.session_activity().session_id().find(...)`.
pub struct SessionActivitySessionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SessionActivity, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SessionActivityTableHandle<'ctx> {
    /// Get a handle on the `session_id` unique index on the table `session_activity`.
    pub fn session_id(&self) -> SessionActivitySessionIdUnique<'ctx> {
        SessionActivitySessionIdUnique {
            imp: self.imp.get_unique_constraint::<String>("session_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SessionActivitySessionIdUnique<'ctx> {
    /// Find the subscribed row whose `session_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SessionActivity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SessionActivity>("session_activity");
    _table.add_unique_constraint::<String>("session_id", |row| &row.session_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SessionActivity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SessionActivity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SessionActivity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait session_activityQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SessionActivity`.
    fn session_activity(&self) -> __sdk::__query_builder::Table<SessionActivity>;
}

impl session_activityQueryTableAccess for __sdk::QueryTableAccessor {
    fn session_activity(&self) -> __sdk::__query_builder::Table<SessionActivity> {
        __sdk::__query_builder::Table::new("session_activity")
    }
}
