// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SessionActivity {
    pub session_id: String,
    pub state: String,
    pub last_tool_event: Option<String>,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SessionActivity {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SessionActivity`.
///
/// Provides typed access to columns for query building.
pub struct SessionActivityCols {
    pub session_id: __sdk::__query_builder::Col<SessionActivity, String>,
    pub state: __sdk::__query_builder::Col<SessionActivity, String>,
    pub last_tool_event: __sdk::__query_builder::Col<SessionActivity, Option<String>>,
    pub updated_at: __sdk::__query_builder::Col<SessionActivity, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SessionActivity {
    type Cols = SessionActivityCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SessionActivityCols {
            session_id: __sdk::__query_builder::Col::new(table_name, "session_id"),
            state: __sdk::__query_builder::Col::new(table_name, "state"),
            last_tool_event: __sdk::__query_builder::Col::new(table_name, "last_tool_event"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SessionActivity`.
///
/// Provides typed access to indexed columns for query building.
pub struct SessionActivityIxCols {
    pub session_id: __sdk::__query_builder::IxCol<SessionActivity, String>,
}

impl __sdk::__query_builder::HasIxCols for SessionActivity {
    type IxCols = SessionActivityIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SessionActivityIxCols {
            session_id: __sdk::__query_builder::IxCol::new(table_name, "session_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SessionActivity {}
