// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetDisplayNameArgs {
    pub name: String,
}

impl From<SetDisplayNameArgs> for super::Reducer {
    fn from(args: SetDisplayNameArgs) -> Self {
        Self::SetDisplayName { name: args.name }
    }
}

impl __sdk::InModule for SetDisplayNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_display_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_display_name {
    /// Request that the remote module invoke the reducer `set_display_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_display_name:set_display_name_then`] to run a callback after the reducer completes.
    fn set_display_name(&self, name: String) -> __sdk::Result<()> {
        self.set_display_name_then(name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_display_name` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_display_name_then(
        &self,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_display_name for super::RemoteReducers {
    fn set_display_name_then(
        &self,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetDisplayNameArgs { name }, callback)
    }
}
