// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetA2AEnabledArgs {
    pub enabled: bool,
}

impl From<SetA2AEnabledArgs> for super::Reducer {
    fn from(args: SetA2AEnabledArgs) -> Self {
        Self::SetA2AEnabled {
            enabled: args.enabled,
        }
    }
}

impl __sdk::InModule for SetA2AEnabledArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_a2a_enabled`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_a_2_a_enabled {
    /// Request that the remote module invoke the reducer `set_a2a_enabled` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_a_2_a_enabled:set_a_2_a_enabled_then`] to run a callback after the reducer completes.
    fn set_a_2_a_enabled(&self, enabled: bool) -> __sdk::Result<()> {
        self.set_a_2_a_enabled_then(enabled, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_a2a_enabled` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_a_2_a_enabled_then(
        &self,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_a_2_a_enabled for super::RemoteReducers {
    fn set_a_2_a_enabled_then(
        &self,
        enabled: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetA2AEnabledArgs { enabled }, callback)
    }
}
