// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SpaceFile {
    pub id: String,
    pub path: String,
    pub name: String,
    pub content: String,
    pub folder_path: String,
    pub depth: u32,
    pub extension: String,
    pub size: u64,
    pub created_time: u64,
    pub modified_time: u64,
    pub db_updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SpaceFile {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SpaceFile`.
///
/// Provides typed access to columns for query building.
pub struct SpaceFileCols {
    pub id: __sdk::__query_builder::Col<SpaceFile, String>,
    pub path: __sdk::__query_builder::Col<SpaceFile, String>,
    pub name: __sdk::__query_builder::Col<SpaceFile, String>,
    pub content: __sdk::__query_builder::Col<SpaceFile, String>,
    pub folder_path: __sdk::__query_builder::Col<SpaceFile, String>,
    pub depth: __sdk::__query_builder::Col<SpaceFile, u32>,
    pub extension: __sdk::__query_builder::Col<SpaceFile, String>,
    pub size: __sdk::__query_builder::Col<SpaceFile, u64>,
    pub created_time: __sdk::__query_builder::Col<SpaceFile, u64>,
    pub modified_time: __sdk::__query_builder::Col<SpaceFile, u64>,
    pub db_updated_at: __sdk::__query_builder::Col<SpaceFile, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SpaceFile {
    type Cols = SpaceFileCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SpaceFileCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            folder_path: __sdk::__query_builder::Col::new(table_name, "folder_path"),
            depth: __sdk::__query_builder::Col::new(table_name, "depth"),
            extension: __sdk::__query_builder::Col::new(table_name, "extension"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            created_time: __sdk::__query_builder::Col::new(table_name, "created_time"),
            modified_time: __sdk::__query_builder::Col::new(table_name, "modified_time"),
            db_updated_at: __sdk::__query_builder::Col::new(table_name, "db_updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SpaceFile`.
///
/// Provides typed access to indexed columns for query building.
pub struct SpaceFileIxCols {
    pub db_updated_at: __sdk::__query_builder::IxCol<SpaceFile, __sdk::Timestamp>,
    pub id: __sdk::__query_builder::IxCol<SpaceFile, String>,
    pub path: __sdk::__query_builder::IxCol<SpaceFile, String>,
}

impl __sdk::__query_builder::HasIxCols for SpaceFile {
    type IxCols = SpaceFileIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SpaceFileIxCols {
            db_updated_at: __sdk::__query_builder::IxCol::new(table_name, "db_updated_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            path: __sdk::__query_builder::IxCol::new(table_name, "path"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SpaceFile {}
