// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::space_file_type::SpaceFile;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `space_file`.
///
/// Obtain a handle from the [`SpaceFileTableAccess::space_file`] method on [`super::RemoteTables`],
/// like `ctx.db.space_file()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.space_file().on_insert(...)`.
pub struct SpaceFileTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpaceFile>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `space_file`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpaceFileTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpaceFileTableHandle`], which mediates access to the table `space_file`.
    fn space_file(&self) -> SpaceFileTableHandle<'_>;
}

impl SpaceFileTableAccess for super::RemoteTables {
    fn space_file(&self) -> SpaceFileTableHandle<'_> {
        SpaceFileTableHandle {
            imp: self.imp.get_table::<SpaceFile>("space_file"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpaceFileInsertCallbackId(__sdk::CallbackId);
pub struct SpaceFileDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpaceFileTableHandle<'ctx> {
    type Row = SpaceFile;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpaceFile> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpaceFileInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpaceFileInsertCallbackId {
        SpaceFileInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpaceFileInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpaceFileDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpaceFileDeleteCallbackId {
        SpaceFileDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpaceFileDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SpaceFileUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpaceFileTableHandle<'ctx> {
    type UpdateCallbackId = SpaceFileUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpaceFileUpdateCallbackId {
        SpaceFileUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpaceFileUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `space_file`,
/// which allows point queries on the field of the same name
/// via the [`SpaceFileIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.space_file().id().find(...)`.
pub struct SpaceFileIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpaceFile, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpaceFileTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `space_file`.
    pub fn id(&self) -> SpaceFileIdUnique<'ctx> {
        SpaceFileIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpaceFileIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SpaceFile> {
        self.imp.find(col_val)
    }
}

/// Access to the `path` unique index on the table `space_file`,
/// which allows point queries on the field of the same name
/// via the [`SpaceFilePathUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.space_file().path().find(...)`.
pub struct SpaceFilePathUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpaceFile, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpaceFileTableHandle<'ctx> {
    /// Get a handle on the `path` unique index on the table `space_file`.
    pub fn path(&self) -> SpaceFilePathUnique<'ctx> {
        SpaceFilePathUnique {
            imp: self.imp.get_unique_constraint::<String>("path"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpaceFilePathUnique<'ctx> {
    /// Find the subscribed row whose `path` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SpaceFile> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpaceFile>("space_file");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("path", |row| &row.path);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SpaceFile>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpaceFile>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SpaceFile`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait space_fileQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SpaceFile`.
    fn space_file(&self) -> __sdk::__query_builder::Table<SpaceFile>;
}

impl space_fileQueryTableAccess for __sdk::QueryTableAccessor {
    fn space_file(&self) -> __sdk::__query_builder::Table<SpaceFile> {
        __sdk::__query_builder::Table::new("space_file")
    }
}
