// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TodoSweepSchedule {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for TodoSweepSchedule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TodoSweepSchedule`.
///
/// Provides typed access to columns for query building.
pub struct TodoSweepScheduleCols {
    pub scheduled_id: __sdk::__query_builder::Col<TodoSweepSchedule, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<TodoSweepSchedule, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for TodoSweepSchedule {
    type Cols = TodoSweepScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TodoSweepScheduleCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TodoSweepSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct TodoSweepScheduleIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<TodoSweepSchedule, u64>,
}

impl __sdk::__query_builder::HasIxCols for TodoSweepSchedule {
    type IxCols = TodoSweepScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TodoSweepScheduleIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TodoSweepSchedule {}
