// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateNotePathArgs {
    pub id: String,
    pub new_path: String,
}

impl From<UpdateNotePathArgs> for super::Reducer {
    fn from(args: UpdateNotePathArgs) -> Self {
        Self::UpdateNotePath {
            id: args.id,
            new_path: args.new_path,
        }
    }
}

impl __sdk::InModule for UpdateNotePathArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_note_path`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_note_path {
    /// Request that the remote module invoke the reducer `update_note_path` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_note_path:update_note_path_then`] to run a callback after the reducer completes.
    fn update_note_path(&self, id: String, new_path: String) -> __sdk::Result<()> {
        self.update_note_path_then(id, new_path, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_note_path` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_note_path_then(
        &self,
        id: String,
        new_path: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_note_path for super::RemoteReducers {
    fn update_note_path_then(
        &self,
        id: String,
        new_path: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateNotePathArgs { id, new_path }, callback)
    }
}
