// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VideoFrame {
    pub call_id: u64,
    pub from: __sdk::Identity,
    pub seq: u32,
    pub codec: u8,
    pub is_keyframe: bool,
    pub data: Vec<u8>,
}

impl __sdk::InModule for VideoFrame {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VideoFrame`.
///
/// Provides typed access to columns for query building.
pub struct VideoFrameCols {
    pub call_id: __sdk::__query_builder::Col<VideoFrame, u64>,
    pub from: __sdk::__query_builder::Col<VideoFrame, __sdk::Identity>,
    pub seq: __sdk::__query_builder::Col<VideoFrame, u32>,
    pub codec: __sdk::__query_builder::Col<VideoFrame, u8>,
    pub is_keyframe: __sdk::__query_builder::Col<VideoFrame, bool>,
    pub data: __sdk::__query_builder::Col<VideoFrame, Vec<u8>>,
}

impl __sdk::__query_builder::HasCols for VideoFrame {
    type Cols = VideoFrameCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VideoFrameCols {
            call_id: __sdk::__query_builder::Col::new(table_name, "call_id"),
            from: __sdk::__query_builder::Col::new(table_name, "from"),
            seq: __sdk::__query_builder::Col::new(table_name, "seq"),
            codec: __sdk::__query_builder::Col::new(table_name, "codec"),
            is_keyframe: __sdk::__query_builder::Col::new(table_name, "is_keyframe"),
            data: __sdk::__query_builder::Col::new(table_name, "data"),
        }
    }
}

/// Indexed column accessor struct for the table `VideoFrame`.
///
/// Provides typed access to indexed columns for query building.
pub struct VideoFrameIxCols {}

impl __sdk::__query_builder::HasIxCols for VideoFrame {
    type IxCols = VideoFrameIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VideoFrameIxCols {}
    }
}
