// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::video_frame_type::VideoFrame;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `video_frame`.
///
/// Obtain a handle from the [`VideoFrameTableAccess::video_frame`] method on [`super::RemoteTables`],
/// like `ctx.db.video_frame()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.video_frame().on_insert(...)`.
pub struct VideoFrameTableHandle<'ctx> {
    imp: __sdk::TableHandle<VideoFrame>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `video_frame`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VideoFrameTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VideoFrameTableHandle`], which mediates access to the table `video_frame`.
    fn video_frame(&self) -> VideoFrameTableHandle<'_>;
}

impl VideoFrameTableAccess for super::RemoteTables {
    fn video_frame(&self) -> VideoFrameTableHandle<'_> {
        VideoFrameTableHandle {
            imp: self.imp.get_table::<VideoFrame>("video_frame"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VideoFrameInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::EventTable for VideoFrameTableHandle<'ctx> {
    type Row = VideoFrame;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VideoFrame> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VideoFrameInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VideoFrameInsertCallbackId {
        VideoFrameInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VideoFrameInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VideoFrame>("video_frame");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VideoFrame>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VideoFrame>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VideoFrame`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait video_frameQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VideoFrame`.
    fn video_frame(&self) -> __sdk::__query_builder::Table<VideoFrame>;
}

impl video_frameQueryTableAccess for __sdk::QueryTableAccessor {
    fn video_frame(&self) -> __sdk::__query_builder::Table<VideoFrame> {
        __sdk::__query_builder::Table::new("video_frame")
    }
}
